### ISSUE TITLE
Cannot validate SSL requests using internal CA.

### ISSUE THREAD

**Issue by mmerickel** [AFNetworking/AFNetworking#2117]
I think this is related to #1852. I'm using 2.2.4.

I have an internal CA cert that I'm shipping with the app and thus it's not in the trusted keychain. I'm using `AFSSLPinningModePublicKey`. I'd prefer to not need to set `allowInvalidCertificates` to `YES` because I am shipping enough certs with the app that the whole chain should be verifiable and pinned.

The following patch fixes this issue but ignores the other pinning modes:

```diff
diff --git a/Vendor/AFNetworking/src/AFNetworking/AFSecurityPolicy.m b/Vendor/AFNetworking/src/AFNetworking/AFSecurityPolicy.m
index 019299f..98b90fe 100644
--- a/Vendor/AFNetworking/src/AFNetworking/AFSecurityPolicy.m
+++ b/Vendor/AFNetworking/src/AFNetworking/AFSecurityPolicy.m
@@ -240,8 +240,13 @@ static NSArray * AFPublicKeyTrustChainForServerTrust(SecTrustRef serverTrust) {
     } else {
         [policies addObject:(__bridge_transfer id)SecPolicyCreateBasicX509()];
     }
-
+    
     SecTrustSetPolicies(serverTrust, (__bridge CFArrayRef)policies);
+    NSMutableArray *pinnedCertificates = [NSMutableArray array];
+    for (NSData *certificateData in self.pinnedCertificates) {
+        [pinnedCertificates addObject:(__bridge_transfer id)SecCertificateCreateWithData(NULL, (__bridge CFDataRef)certificateData)];
+    }
+    SecTrustSetAnchorCertificates(serverTrust, (__bridge CFArrayRef)pinnedCertificates);
 
     if (!AFServerTrustIsValid(serverTrust) && !self.allowInvalidCertificates) {
         return NO;
```

**Comment by cognitiveflux** [comment]
Have you received any feedback on your recommended patch?

The question I'm trying to answer is the intended purpose of the `validatesCertificateChain` attribute.  I would expect this to refer to whether the *chain* is **cryptographically valid**, but it appears that in the [implementation](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFSecurityPolicy.m#L261-306) it is comparing presence of each certificate in the chain from the server with each certificate bundled in the app.  This doesn't make any sense to me, it should be validating that the root anchor is valid and not doing a one-for-one presence and equality comparison, which effectively is the same thing as certificate pinning (instead of public key pinning).

[This check](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFSecurityPolicy.m#L257-259) completely ignores any certificate in the app bundle as a potential trust anchor, so it negates any pinning against included certificates from a **non public** certificate authority; isn't the point of pinning to bypass the public CA network and define your own root authority?  Those lines should really only be part of the `AFSSLPinningModeNone` case because it is effectively checking if the server certificate is valid against the *default* trust store.  If other pinning modes are used, the assumption is that we want to check against something *other* than the default trust store.

Moving those lines to the `AFSSLPinningModeNone` case and changing [all of this](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFSecurityPolicy.m#L290-304) with the following would resolve the issues, yes?:

```Objective-C
NSMutableArray *pinnedCertificates = [NSMutableArray array];
for (NSData *certificateData in self.pinnedCertificates) {
   [pinnedCertificates addObject:(__bridge_transfer id)SecCertificateCreateWithData(NULL, (__bridge CFDataRef)certificateData)];
}
SecTrustSetAnchorCertificates(serverTrust, (__bridge CFArrayRef)pinnedCertificates);
return AFServerTrustIsValid(serverTrust)
```

From the Apple API documentation:
> As an exception, if your app has previously called SecTrustSetAnchorCertificates, the user-specified trust settings are ignored, and the certificate’s chain must contain one of the specified anchor certificates.

After we add the certificate(s) in the app bundle to the trust store, checking for validity against the trust store with the new anchor(s) should be the only thing required for PublicKey validation, correct?

**Comment by kcharwood** [comment]
I believe the updates 2.6.0 addressed these issues. If you are still running into issues, you can reopen this issue.

:beers:
