### ISSUE TITLE
AFNetworkActivityIndicatorManager taskDidResume erratic crash

### ISSUE THREAD

**Issue by soundspectrum** [AFNetworking/AFNetworking#2439]
Hi Matt!

Firstly, many thanks for your hard work in AFN and I've done my best to make sure the issue isn't on my end!

I'm using a UIRefreshControl in a UITableViewController similar to how GlobalTimelineViewController uses one in the AFNetworking example.  However, after 3-5 table refreshes, I'm getting a unrecognized selector crash when AFURLSessionManager's  `taskDidResume:` (AFURLSessionManager.m:402) is trying to send a `AFNetworkingTaskDidResumeNotification` to `networkRequestDidStart:` of an instance of AFNetworkActivityIndicatorManager.  

This issue occurred in rev 29511 and still occurs in the latest  29542, so this is not newly introduced.

Separately, I wanted to point out that the property `refreshControl` is redundant in GlobalTimelineViewController.m:34 since it's also available in UITableViewController.

Thanks,
Drew

**Comment by sudhanshutil** [comment]
Any update regarding the issue? I am also having this issue some times.

**Comment by soundspectrum** [comment]
Update!

I'm not sure if the issue is officially in AF, but since I filed this I've revamped our table reloading sequence and the problem has gone away.  Multiple table reloads were being ordered before they were complete (ie reloadData was being called multiple times inadvertently before the proceeding one was complete).  So my best guess what was causing this issue (and what is causing similar issues for others), is that UIKit is smashing who knows what when reloadData is called improperly and by the time AF accesses various elements, something is junked).  So, although an issue may still be lurking in AF, it's likely that you're unknowingly thrashing something due to volatile table data refreshing.  

Matt, if you want to close this, I'm down!

**Comment by mattt** [comment]
Thanks, @soundspectrum. I'm glad to hear that you found a resolution to your problem.

**Comment by Soundfiler** [comment]
PLEASE STOP SPAMMING ME!!!

Am Samstag, 2. Mai 2015 schrieb Mattt Thompson :

> Thanks, @soundspectrum <https://github.com/soundspectrum>. I'm glad to
> hear that you found a resolution to your problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AFNetworking/AFNetworking/issues/2439#issuecomment-98398168>
> .
>


-- 
Von meinem iPhone via Gmail

**Comment by mattt** [comment]
@Soundfiler If you are receiving unwanted notifications, you should adjust your GitHub notification settings accordingly.

**Comment by jam** [comment]
@soundspectrum: Any chance you know what specifically resolved this? I'm running into exactly the same thing today :confused: The network request code has remained untouched for the last several months. These are local network requests, so will probably finish quickly as you said, but it hasn't given us any trouble in the past.

**Comment by Bluezen** [comment]
I had the exact same crash and I don't know about @soundspectrum but in my `UITableViewController` I am making use of AFNetworking category on UIRefreshControl with:
``` objc
[self.refreshControl setRefreshingWithStateOfTask:myTask];
```
which do:
```objc
[notificationCenter addObserver:self selector:@selector(af_endRefreshing) name:AFNetworkingTaskDidCompleteNotification object:task];
```
Removing the refreshControler as an observer in the dealloc prevented me to see this crash again:
```objc
-(void)dealloc
{
    [[NSNotificationCenter defaultCenter] removeObserver:self.refreshControl];
}
```

**Comment by sergiou87** [comment]
I think I have found the problem :smile: 

If I'm right, the problem was this:
 1. Thread A: `- [NSURLSessionDataTask resume]` is called. The swizzled method `af_resume` posts a `AFNSURLSessionTaskDidResumeNotification` notification. The callback for that notification is not invoked (yet).
 2. Thread B: an instance of `AFHTTPSessionManager` is deallocated. That means, it removes itself as observer of `AFNSURLSessionTaskDidResumeNotification` (but now it's too late!).
 3. Thread A: the callback of `AFNSURLSessionTaskDidResumeNotification` is invoked (`-[AFURLSessionManager taskDidResume:]`) in the instance deallocated in thread B (step 2) and tries to access a property of it.
 4. CRASH!!!


You can reproduce it with the following code in your AppDelegate (you may need to run it several times, and each time you will get different crashes depending on when it switches between threads). This doesn't happen if you built the app with iOS 9 SDK and running on iOS 9, because of the changes Apple introduced on `NSNotificationCenter`, but it definitely happens on iOS 8 (no matter what SDK you used) and iOS 9 if the app was built with iOS 8 SDK.

The numbers for the iterations (and even part of the code) is kind of random, I just wanted to copy the exact code that reproduced the problem. It just creates a bunch of `AFHTTPSessionManager` with short life-span, and concurrently creates tasks and resumes them.

```objective-c
#import "AFNetworking.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    AFHTTPSessionManager *sm = [[AFHTTPSessionManager alloc] initWithBaseURL:[NSURL URLWithString:@"http://127.0.0.1:8080"]];

    for (NSUInteger k=0; k < 20; k++)
    {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
            for (NSUInteger i=0; i < 100; i++)
            {
                NSURLSessionDataTask *task = [sm dataTaskWithRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"http://127.0.0.1:8080"]] completionHandler:nil];
                [task resume];

            }
        });

        for (NSUInteger i=0; i < 100; i++)
        {
            @autoreleasepool {
                AFHTTPSessionManager *j = [[AFHTTPSessionManager alloc] initWithBaseURL:[NSURL URLWithString:@"http://127.0.0.1:8080"]];

                [j invalidateSessionCancelingTasks:YES];
            }
        }
    }

    return YES;
}
```

The pull request that solves this: https://github.com/AFNetworking/AFNetworking/pull/3023
