### ISSUE TITLE
Multiple AFURLSessionManagers + AFNetworkActivityIndicatorManager = never-ending activity indicator

### ISSUE THREAD

**Issue by tangphillip** [AFNetworking/AFNetworking#2476]
When using multiple `AFURLSessionManager`s, AFNetworking generates many extraneous `AFNetworkingTaskDidResumeNotification` notifications, causing the `AFNetworkActivityIndicatorManager` to show the activity indicator permanently.

Sample project demonstrating the issue, courtesy of @eytanbiala: https://dl.dropboxusercontent.com/u/3067376/AFNetworkingTest-2458.zip

**Root cause:** `AFURLSessionManager`s were determining that tasks belong to them...when they really don't. Managers were using, "Do I have a task with this `taskIdentifier`?" as shorthand for, "Was this task created by me?" Unfortunately, `taskIdentifier`s are unique only within their `NSURLSession`, and therefore any given identifier can be (and frequently is) used in multiple sessions at the same time.

**Comment by phoney** [comment]
I have also run into this bug (and spent an inordinate amount of time tracking it down). 

Your fix gets to the heart of the matter but I don't think it's a good idea to commandeer the taskDescription for this purpose. This will interfere with developers using the taskDescription for their own purposes. I use the taskDescription in my own code for background download tasks. I save the file path where the file is to be saved in the taskDescription.

The underlying bug is due to the taskIdentifier not being unique across the entire app but only across each session manager, as you say. Therefore it was a mistake to use the taskIdentifier as the key for the mutableTaskDelegatesKeyedByTaskIdentifier dictionary. So another simple fix is to change the key from the taskIdentifier to the task pointer. Something like this

    delegate = self.mutableTaskDelegatesKeyedByTaskIdentifier[@((NSUInteger) task)];

in three places fixes the bug as well. I guess you'll want to change the name of the dictionary too. This would be almost the same as your fix but would avoid using the taskDescription.

**Comment by tangphillip** [comment]
If we can rely on `NSURLSessionTask` having a consistent pointer throughout its life, that's a good solution.

`NSURLSessionTask` conforms to `NSCopying`. What would happen if I made a `copy` of a task? I don't know enough about `NSURLSession` to decide if that's a thing worth supporting.

**Comment by phoney** [comment]
I don't think copying is an issue. Yes, a copy would get a new address. But a copy wouldn't belong to our AFURLSessionManager.

Other solutions that come to mind are 
to simply keep a list of active session tasks inside each AFURLSessionManger. 
To use the [self.session getTasksWithCompletionHandler:] method inside taskDidResume to determine if the task is owned. 
To add an ivar to NSURLSessionTask to track its current owner with objc_setAssociatedObject, much like your taskDescription solution. 

I don't really like any of those though.

**Comment by ronak2121** [comment]
Confirm that we are also facing this same issue. I think the least expensive and intrusive solution is to use the ivar with objc_setAssociatedObject. 

Other ideas we could do is to hash the combination of the original request url and the task identifier; as those don't change for the life of the NSURLSessionTask. This has a low chance of colliding with other tasks on other session managers concurrently; but still may.

**Comment by ronak2121** [comment]
By overwriting the task description, this prevents applications from using that field for their own purposes. For example this breaks the work I did for background transfer support in our app.

Why did you decide to overwrite the task description vs some of the other approaches?

**Comment by tangphillip** [comment]
The patch was merged before I had the chance to edit it to do otherwise. If you'd like to see it use another approach, submit a PR!

**Comment by kobelb** [comment]
For what it matters, I sympathize with @ronak2121  and @phoney, and I was using the taskDescription to keep track of background uploads, and I'm now no longer able to do so.

**Comment by phoney** [comment]
FWIW, it seems that the taskDescription is only used by AFNetworking between the time the task is created and when it's resumed. By setting the taskDescription to my value after the resume things seem to work correctly regarding the activity indicator (except for background downloads as described in my issue https://github.com/AFNetworking/AFNetworking/issues/2660). I don't know if there are any cases where tasks would be resumed more than once.

Having said that, I think using the task pointer as the key in the mutableTaskDelegatesKeyedByTaskIdentifier dictionary is a better way.

Also, recent changes to the swizzling code seem to have broken this code again for iOS 7.x
