### ISSUE TITLE
Facilitate more extensible AFSecurityPolicy mechanism

### ISSUE THREAD

**Issue by Aronax666** [AFNetworking/AFNetworking#2503]
Hi,

I started looking into AFSecurityPolicy (version 2.5.0) and extension mechanism to implement stricter validation. There are a couple of things that prevent me from doing this cleanly and have some weird side-effects.

1) AFSecurityPolicy is class instead of a protocol.

The only two methods used by the AFNetworking itself are:
 - (BOOL)evaluateServerTrust:forDomain: and + (instancetype)defaultPolicy;

If there was a base protocol that provides only   - (BOOL)evaluateServerTrust:forDomain: it would be much easier to add custom implementations of security policy.

DefaultPolicy would simply be one implementation of this protocol provided by AFNetworking, used internally as fallback.

2) There is no way to instantiate clean AFSecurityPolicy item and then set the pinning mode.

When calling [AFSecurityPolicy policyWithPinningMode:<any option>] it always triggers internally [securityPolicy setPinnedCertificates:[self defaultPinnedCertificates]]; which in turn tries to read all the certificates from the bundle/disk. 
For some purposes such side-effect is not acceptable.

3) Default policy is always set first when instantiating AFURLConnectionOperation and it's subclasses. There is no way to instantiate it with some specific policy. This one is a minor currently since default policy does nothing special, but if it does change in the future that could be a problem (like 2)).

4) Mode that doesn't trust system CA store.

allowInvalidCertificates sounds misleading, because in some use cases it's much better NOT to trust CA store of the system and pin against a single self signed certificate (which is then rotated with application updates).

A nice explanation/rationale can be found here: http://www.thoughtcrime.org/blog/authenticity-is-broken-in-ssl-but-your-app-ha/

5) default implentation of - (void)connection:willSendRequestForAuthenticationChallenge: could pass the protectionSpace to the AFSecurityPolicy instead of just - (BOOL)evaluateServerTrust:forDomain:

Currently there is no way to validate protocol and other potentially interesting information without reimplementing all other details through self.authenticationChallenge block.

Cheers,
A

**Comment by mattt** [comment]
Thanks for your thoughtful feedback, @Aronax666. Responding point-by-point:

> 1) AFSecurityPolicy is class instead of a protocol.

`AFSecurityPolicy` is provided as-is for convenient validation of the most common security behaviors. For anything else, the API consumer should set a custom `sessionDidReceiveAuthenticationChallenge` handler for their manager. A protocol would only be appropriate if there were not a standard way to authenticate connections to servers. If there _is_ anything that should be done differently, that behavior should be changed in `AFSecurityPolicy` itself.

> 2) There is no way to instantiate clean AFSecurityPolicy item and then set the pinning mode.

This is by design. There is no reason for `pinningMode` to be mutable.

> 3) Default policy is always set first when instantiating AFURLConnectionOperation and it's subclasses. 

If you want something else, just set a new policy after initialization.

> 4) Mode that doesn't trust system CA store.
> 5) default implentation of - (void)connection:willSendRequestForAuthenticationChallenge: could pass the protectionSpace to the `AFSecurityPolicy`...

I'd welcome a PR with specific proposed changes.
