### ISSUE TITLE
NSMutableURLRequest setTimeoutInterval: method works on WIFI but not on GSM

### ISSUE THREAD

**Issue by aolszak** [AFNetworking/AFNetworking#2529]
I'm struggling with one weird situation while trying to make quite long request on the server with AFNetworking over HTTP POST.

Entry informations which I have checked and are true in my situation:
- request limit on the server is set to 300s
- default timeout for NSMutableURLRequest is 60s

Problem starts when I'm trying to assign timeout limit
[request setTimeoutInterval:180];

After some research I have found that:
- assigned limit works while using local WIFI network
- assigned limit DO NOT work while using sim card and GSM network

I was unable to find any concrete informations about this problem.

**Comment by mattt** [comment]
This is not entirely unexpected behavior, as both iOS and mobile providers have a history of disregarding prescribed timeouts in unexpected ways in order to facilitate better performance over cellular networks.

Either way, this is all on the Foundation URL Loading System; unfortunately, AFNetworking has no control over any of that.
