### ISSUE TITLE
Change proposal: extract a generic state tracking object from AFNetworkActivityIndicatorManager

### ISSUE THREAD

**Issue by matt-holden** [AFNetworking/AFNetworking#2578]
__I'm interested in writing and submitting a pull request for this change, but I'd rather hear from the project's maintainers first to see if it would be welcomed.__

I recently wanted to implement custom "loading" behavior at a top level of my application.  

My options, at present are:

1. Use  `AFNetworkActivityIndicatorManager` instead of custom UI
2. Subscribe to `AFNetworkingOperationDidStartNotification`, etc.. and increment/decrement my own `activityCount` variable.

What I really wanted the convenience of an AFNetworking-managed block-based API, something like:

```objc
[[AFNetworkActivityState(?) sharedState] observeActivityStateWithBlock:^(AFNetworkActivity state) {
  if (state == AFNetworkActivityStateActive) {
     // show my custom "Loading" over the root view controller
  } else {
    // hide my custom "Loading" indicator
  }
}];
```

It appears that the code in `AFNetworkActivityIndicatorManager` could easily be split up into two separate pieces:

1. An object that tracks overall state, with a public API similar to the code block above
2. The existing `AFNetworkingActivityIndicatorManager`, but with slimmed-down internals -- it would leverage the new state-monitoring object instead of tracking the global activity count itself.

Any thoughts?

**Comment by mattt** [comment]
The notifications are provided so that anyone wanting to build a monitoring service (such as [AFNetworkActivityLogger](https://github.com/AFNetworking/AFNetworkActivityLogger)) can do so easily. `AFNetworkActivityIndicatorManager` is provided as a convenient component for a majority of apps that implement that standard UI element. There's no compelling reason to open up the API any more than it already is for further customization.

**Comment by matt-holden** [comment]
Fair enough :-)

Thanks for the fast reply.
