### ISSUE TITLE
Download image, the progress is 100%, but completionHandler be called about several seconds later

### ISSUE THREAD

**Issue by zhw511006** [AFNetworking/AFNetworking#2580]
I download a image by NSURLSessionDownloadTask, when the progress is 100%,  but completionHandler can't execute, about several seconds it will be called (I think image size impact this)

```objective-c
AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:sessionConfiguration];
    
    NSURLSessionDownloadTask *downloadTask = [manager downloadTaskWithRequest:[NSURLRequest requestWithURL:pURL]
                                                                     progress:&progress
                                                                  destination:^NSURL *(NSURL *targetPath, NSURLResponse *response) {
                                                                      return [NSURL fileURLWithPath:pCachePath];
                                                                  }
                                                            completionHandler:^(NSURLResponse *response, NSURL *filePath, NSError *error) {
                                                               
                                                            }];
    
    [downloadTask resume];
```

What's your suggestions? Thx!

**Comment by mattt** [comment]
There are several possible explanations for the latency between 100% progress and the completion block being called: incorrect content size being reported by the server, incorrect content size being calculated due to gzip compression, slow disk write on download, or the completion handler performing expensive operations before a log statement. Without a reproducible example, this can't be investigated as a framework bug.

If this is a recurring issue, I would encourage you to ask about it on Stack Overflow.

**Comment by zhw511006** [comment]
http://stackoverflow.com/questions/28942632/afnetworking-download-images-the-progress-is-100-but-completionhandler-be-ca

Please go to this link and give some suggestions, Thanks!
