### ISSUE TITLE
Request to make a method public in AFHTTPRequestOperationManager

### ISSUE THREAD

**Issue by rdoddi** [AFNetworking/AFNetworking#2591]
It will be convenient to create and customize AFHTTPRequestOperation using following method which is declared as private. Would it be possible to make this public.

// Class: AFHTTPRequestOperationManager
```
- (AFHTTPRequestOperation *)HTTPRequestOperationWithHTTPMethod:(NSString *)method
                                                     URLString:(NSString *)URLString
                                                    parameters:(id)parameters
                                                       success:(void (^)(AFHTTPRequestOperation *operation, id responseObject))success
                                                       failure:(void (^)(AFHTTPRequestOperation *operation, NSError *error))failure;
```

**Comment by mattt** [comment]
As per the documentation, the method you're looking for it `HTTPRequestOperationWithRequest:success:failure:`. `HTTPRequestOperationWithHTTPMethod: URLString:parameters:success:failure:` doesn't do anything really interesting other than delegating to `HTTPRequestOperationWithRequest:success:failure`.

**Comment by slabko** [comment]
I just tried to to implement a simular method and ended up doing absolutely the same what is already done in the private method `HTTPRequestOperationWithHTTPMethod:URLString:parameters:success:failure:`. It's logically trivial, although it does some work, more that simply calling `HTTPRequestOperationWithRequest:success:failure:`. For example it takes care of serializing errors and it is more that one or two lines of code already.

So basically what I need (and other people as well, I guess), is the ability to make different requests by calling the same method with one additional parameter: HTTP method. `HTTPRequestOperationWithHTTPMethod: URLString:parameters:success:failure:` is exactly a solution.

Here is a use case for a metod that requires the HTTP method. Imagine I have an object which I can ether create (POST) or update (PUT). The request is simple and the completion handlers are the same. The only difference is the HTTP method. I have two options here:

1. Call `PUT:parameters:success:failure:` and `POST:parameters:success:failure:` with the same completion handlers and parameters. I tried, and doesn't look nice, actually.
2. Create a method wich does the same as `HTTPRequestOperationWithHTTPMethod:URLString:parameters:success:failure:`, and by doing that I actually will do the same what is already done in `HTTPRequestOperationWithHTTPMethod:URLString:parameters:success:failure:`, and that looks mostly the same:

```
- (AFHTTPRequestOperation *)POST:(NSString *)URLString
                      parameters:(id)parameters
       constructingBodyWithBlock:(void (^)(id <AFMultipartFormData> formData))block
                         success:(void (^)(AFHTTPRequestOperation *operation, id responseObject))success
                         failure:(void (^)(AFHTTPRequestOperation *operation, NSError *error))failure
{
    NSError *serializationError = nil;
    NSMutableURLRequest *request = [self.requestSerializer multipartFormRequestWithMethod:@"POST" URLString:[[NSURL URLWithString:URLString relativeToURL:self.baseURL] absoluteString] parameters:parameters constructingBodyWithBlock:block error:&serializationError];
    if (serializationError) {
        if (failure) {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgnu"
            dispatch_async(self.completionQueue ?: dispatch_get_main_queue(), ^{
                failure(nil, serializationError);
            });
#pragma clang diagnostic pop
        }

        return nil;
    }

    AFHTTPRequestOperation *operation = [self HTTPRequestOperationWithRequest:request success:success failure:failure];

    [self.operationQueue addOperation:operation];

    return operation;
}
```

I can't say that that method simple delegates something to someone, that guy is pretty smart and has some logic here.

On the other hand, such a methods like `GET:parameters:success:failure:` or `POST:parameters:success:failure:` also do nothing, rather than calling `HTTPRequestOperationWithHTTPMethod: URLString:parameters:success:failure:`, which also delegates everything to `HTTPRequestOperationWithRequest:success:failure:`, but those methods exist. And those methods actually much simpler and they really have one couple of lines and they really just delegate something to someone.
