### ISSUE TITLE
Subsequent Request takes too long

### ISSUE THREAD

**Issue by fwhenin** [AFNetworking/AFNetworking#2644]
So after a specific page loads just fine (in under 0.3 seconds), the request After that takes about 25 seconds...no matter what page it's on, if I'm reloading current page then it'll take 25 seconds (and every time I reload that page it takes 25 seconds). Once I go to another page that requires loading a request, it'll take 25 seconds, but then any request after that it's really quick.

Example:
I have 3 pages in my app that each load something, any request after page 3 will take very long (20 to 30 seconds). even the AFNetworkActivityLogger shows 25 seconds
1- request on page 1: OK
2- request on page 2: OK
3- request on page 3: OK
4- reload on page 3: LONG
5- reload page 3 again: LONG
6- reload page 2: LONG
7- reload page 2 again: OK

**Comment by mattt** [comment]
I cannot reproduce. If anything, this sounds like either a server issue or a misconfigured cache, but this isn't really actionable unless a reproducible example can be provided.

If you suspect that it might just be usage, try asking on Stack Overflow. Otherwise, please open a new issue once you can recreate this behavior in a small, isolated example.
