### ISSUE TITLE
AFHTTPSessionManager does not call setQueryStringSerializationWithBlock

### ISSUE THREAD

**Issue by tdquangad2** [AFNetworking/AFNetworking#2653]
I use AFHTTPSessionManager to request json string and set 'setQueryStringSerializationWithBlock' , but this block is not called. This is my code:

    [self.requestSerializer setQueryStringSerializationWithBlock:^NSString *(NSURLRequest *request, id parameters, NSError *__autoreleasing *error) {
        return String;
    }];
     
    [self POST:path parameters:String success:^(NSURLSessionDataTask *task, id responseObject) {
        if (success) {
            success(task,responseObject);
        }
    } failure:^(NSURLSessionDataTask *task, NSError *error) {
        if (failure) {
            failure(task,error);
        }
    }];

**Comment by mattt** [comment]
There is a [passing test](https://github.com/AFNetworking/AFNetworking/blob/master/Tests/Tests/AFHTTPRequestSerializationTests.m#L90-L104) demonstrating the query string serialization block working correctly. If it's not being used, it's because the request serializer does not use it to encode parameters in an HTTP body for `POST` requests, as is the case for JSON request serialization.
