### ISSUE TITLE
Release 2.5.3

### ISSUE THREAD

**Issue by streeter** [AFNetworking/AFNetworking#2655]
It would be great to release 2.5.3 so that we can get a fix for https://github.com/AFNetworking/AFNetworking/pull/2634, which is a regression from 2.5.1. We would like to upgrade to get the security fix in https://github.com/AFNetworking/AFNetworking/pull/2611, but can't until the reachability issue has been addressed.

**Comment by tewha** [comment]
Why would you need reliable results from Reachability? You know networking is unreliable in practice, and that Reachability is for diagnostic not gating, right?

**Comment by streeter** [comment]
Right. Checking for reachability is no substitute for robust error handling. Having reachability checks can be useful in situations where you might want to show a placeholder asking to user to connect to a network. Reachability says that packets can leave the device, but doesn't give any indication whether the packet reached the end target (which is fine).

**Comment by tewha** [comment]
Reachability can also be wrong about whether packets can leave the device. It will tell you if you're connected, but trying to actually do networking can cause the connection to occur.

I'm not saying the bug shouldn't be fixed, only that I hope you're not holding packets back waiting for Reachability. :) See Safari for iPhone and iPad. When it can't load a page, it will automatically load the page when there's a connection… but you can also tap the reload button because Apple knows sometimes it works anyway.

**Comment by streeter** [comment]
Nope, I believe you're correct. The comment's on [Mike Ash's post](https://mikeash.com/pyblog/friday-qa-2013-06-14-reachability.html#comment-a73d576180a1a8fdc39e832cdcd5e3b9) confirm it.

Mostly just want to get the regression fix in an official release.

**Comment by mattt** [comment]
2.5.3 is now available.

**Comment by tewha** [comment]
Thanks @streeter. I made a few comments there on Reachability, but I never saw the pile on after. :)
