### ISSUE TITLE
SNI support in AFNetworking

### ISSUE THREAD

**Issue by manish-finoit** [AFNetworking/AFNetworking#2715]
I have a root certificate that is used to sign with different sub-domain names on the server which is basically implementation of SNI in backend. Now How can I use that certificate and sub-domain name to validate the request.

**Comment by mattt** [comment]
I'm sorry you're experiencing difficulties getting a solution to work for your particular use case. However, we don't use GitHub as a support forum. For usage questions, please try Stack Overflow. Otherwise, I would encourage you to consult the [AFNetworking documentation](http://cocoadocs.org/docsets/AFNetworking/2.5.4/) as well as Apple's [Foundation URL Loading System Programming Guide](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/URLLoadingSystem/URLLoadingSystem.html).
