### ISSUE TITLE
SSL Pinning: What Should Be Certificate Chain Validation Expected Behavior?

### ISSUE THREAD

**Issue by kcharwood** [AFNetworking/AFNetworking#2744]
I've been spending some time deep in the `AFSecurityPolicy` class lately, and I'm wanting to get some feedback from the AFNetworking community on what the various needs are out there.

In AFNetworking, you can currently either pin against the leaf certificate, or the entire chain itself. There is no way to pin against only an intermediate certificate (B in the diagram below), or a subset of the chain (A and B in the diagram below). It's my understanding that there are some people who would want to only pin against an intermediate certificate, or a subset of chain, to allow for production/development certs, and the exchange of new certificates, while limiting the scope of authenticated connections to only be from the intermediate chain.

* A (root)
   * B
      * C (leaf)

The big question: **Is this something worth supporting?** Are there any major security cons to this approach?

Follow up question: **Should you be able to provide multiple pinning chains to check against?** For example, in #2733 there is the concept of providing a backup key should one be needed in the future. Would it make sense to expose a backup chain, and allow the developer to provide multiple valid chains to check (essentially ORing them together?) That could potentially make dev server/production server management a bit easier as well.

**Comment by kcharwood** [comment]
#2646 is one way to solve this.

**Comment by reedloden** [comment]
@kcharwood, as requested, questions answered below.

**Is this something worth supporting?**

Definitely. It's not a good idea at all to pin to an EE (end-entity aka leaf) cert except in very limited circumstances. EE certs are meant to be short-lived (only a few years at max), which means old clients will just stop working once they expire. As such, it's way better to pin to a set of root CAs or intermediate CAs (root CAs are greatly preferred, unless the intermediate CA is specific to your company/organization).

My comment in https://github.com/AFNetworking/AFNetworking/issues/1852#issuecomment-36199389 explains some of the finer points, including linking to several blog posts from experts in this field about how pinning should work.

**Are there any major security cons to this approach?**

Obviously, the higher you pin, the more possible it is for another (possibly malicious) entity to also get a certificate that would be valid under your pinning configuration. However, pinning to just a few root CAs is far better than permitting all 200+ root CAs to be able to MITM your connection. It's a risk trade-off. The closer you go to the actual cert, the more likely it is that you'll need to update more frequently and potentially have broken clients.

**Should you be able to provide multiple pinning chains to check against?**

Yes, should support multiple pins. Take a look [here](https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.json) to see how Twitter, Google, Dropbox, Facebook, and others all have a number of root CAs they pin to. This helps in an emergency when your main CA has issues (or changes their chain for some reason, causing your pinning to have issues).

Hope this helps!

**Comment by kcharwood** [comment]
Thanks @reedloden. Is there any value in pinning the entire chain, or a subset of the chain? Or should we just be pinning against a single cert *somewhere* in the chain (the higher you go, the less secure)?

**Comment by reedloden** [comment]
I don't really see value in that, and I worry it might cause people to make decisions that only hurt them later (especially if they pin too much and really hurt themselves). Single certs are generally fine and are what is used by most other pinning implementations (basically, start at the leaf, and walk up the chain until you find a match (or not)). The only other counter-example I can think of off the top of my head is that nginx does [something different](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_trusted_certificate) for validating client certificates and OCSP responses (they require the full chain from EE to root CA).

**Comment by Jesper84** [comment]
We're currently in a situation, where a customer (a department in a bigger corporation) is now talking about pinning. But since the department who owns the app that we're making, does not control the leaf certificates fully, pinning was skipped previously due to the fact that @reedloden mentions: the risk of broken clients due to renewal of the certificates. So what we are thinking, is to validate against the intermediate certificates instead, hence the PR #2646

**Comment by reedloden** [comment]
@Jesper84, intermediates aren't generally meant to be long-lived, so I would be careful with using them vs. the actual root CAs themselves. You should talk to your CA and find out what their policy is regarding lifetime of intermediates.

**Comment by Jesper84** [comment]
Thanks for the advice. The guys responsible (and those with the knowledge) of the certificates are right know discussing the case. We might go after the root certificates, which we originally intended.

**Comment by arein** [comment]
Hi,

I address various of your points in [2733](https://github.com/AFNetworking/AFNetworking/pull/2733):

1. Backup keys are supported when `validatesCertificateChain` is set to `NO` (complies with the current implementation)
2. Any certificate in the chain can be pinned when  `validatesCertificateChain` is set to `NO`

I like my implementation as it is __backwards compatible__.

Whaddaya think?

**Comment by kcharwood** [comment]
@OliverLetterer, would love your thoughts here as well.

**Comment by kcharwood** [comment]
@reedloden I'd also like your take on domain name validation, and some of the nuance's there. If a developer passes in a domain name, we create a [SecPolicyCreateSSL](https://developer.apple.com/library/prerelease/ios/documentation/Security/Reference/certifkeytrustservices/index.html#//apple_ref/c/func/SecPolicyCreateSSL), which takes in an optional hostname parameter:

> *hostname* If you specify a value for this parameter, the policy will require the specified value to match the host name in the leaf certificate.

That definition makes me believe that is only for leaf certificates, not intermediate or root certificates. Can you comment on the value of host/domain name validation on the client side, and what are the best cases to use that feature?

I'd also like your feedback on when it is worth using (if there is a case). Thanks again!

**Comment by OliverLetterer** [comment]
@kcharwood thanks for reaching out. I happy to share my two cents on this topic :) I agree with very much of what @reedloden said:

__Is this something worth supporting?__

```
Definitely. It's not a good idea at all to pin to an EE (end-entity aka leaf) cert except in very limited circumstances. EE certs are meant to be short-lived (only a few years at max), which means old clients will just stop working once they expire. As such, it's way better to pin to a set of root CAs or intermediate CAs (root CAs are greatly preferred, unless the intermediate CA is specific to your company/organization).
```

I believe being able to pin specific leaf certificates is actually a good idea in more than "very limited circumstances" if one imagines to pin the leaf certificate's public key instead of the actual certificate itself.  The certificate itself might be short lived but not necessarily the public key. Another use case I can think of are banking apps which probably don't care about old clients breaking but rather ensuring the user that they are communicating with the correct host.

__Should you be able to provide multiple pinning chains to check against?__

```
Yes, should support multiple pins. Take a look here to see how Twitter, Google, Dropbox, Facebook, and others all have a number of root CAs they pin to. This helps in an emergency when your main CA has issues (or changes their chain for some reason, causing your pinning to have issues).
```

Huge +1 from my end on multiple pinning chains. Because of different parties having different needs for certificate pinning (everything between pinning a single leaf's public key to pinning multiple whole certificate chains for different backends), my idea would be to make AFSecurityPolicy more open, composable and maybe extensible. `Single certs are generally fine and are what is used by most other pinning implementations`. I totally agree with the general case and I believe that should be the default case. But I would love to be able to define a chains of trust based on certificates, public keys and domain names I explicitly whitelist. Similar to how NSCompoundPredicate allows concatenating predicates with `and` or `or`, I can imaging being able to specify chains of trust, where a single chain can for example `contain public key of leaf certificate C and be originated from root certificate A`, and then trust any of such defined chains.

**Comment by kcharwood** [comment]
Thanks @OliverLetterer!

I'm also interested in knowing if there is a specific security vulnerability that is addressed by pinning against an entire chain (or a subset of the chain), vs pinning against a single certificate in the chain. In my example in the original post, if you pin against B or C, is there any actual value in also pinning against A? Since B and C are derived from A, what value would a developer get out of pinning against A, other than feeling "super, duper" secure. I would love some specific security holes that that feature would address.

Maybe @reedloden has an opinion there too. And thanks again! This issue is very enlightening so far.

**Comment by arein** [comment]
@OliverLetterer: Thanks!

About Public Key Pinning: As far as I understand it is best practice to pin not just the public key but the SPKI (see [Adam's blog post](http://goo.gl/AIx3e5)). This is also how Chromium is implemented.

Am I right that this does not provide any security benefit when  `validatesDomainName` is set to `YES` as the domain name is already validated?

**Comment by kcharwood** [comment]
pinging @OliverLetterer and @reedloden in case you guys have a chance to view my follow up questions above!

Thanks.

**Comment by OliverLetterer** [comment]
@arein +1 on checking SubjectPublicKeyInfo instead of the public key.

@kcharwood I think there is an advantage greater that `feeling "super, duper" secure` when pinning an entire chain instead of a subset. Imagine a larger corporation with a complete private chain who is pinning all public keys to prevent any kind of private key theft. Well this is actually a case of `feeling "super, duper" secure` but I think a legitimate one.

**Comment by reedloden** [comment]
Agree on use of SPKI. Sorry for not clarifying that earlier.

While I don't have any issues with supporting pinning of a full chain, I'm skeptical about people doing it right and not shooting themselves in the foot. Definitely something to warn against unless they are really, really sure they know what they are doing. It really sucks to add TLS pinning and then 12 months down the road find you're now screwed and might lose a lot of users still using old client versions because of bad design decisions. Definitely seen that happen, so just don't want to see documentation or examples that give people bad ideas of what a good/reasonable pinning implementation should be like.

**Comment by OliverLetterer** [comment]
Totally agree with `not shooting themselves in the foot`. How about by default, the new implementation trusts any public key that is contained in any bundle of the application (thinking about the main app's bundle, any extension bundles and any shipping framework bundles). So the default case involves not writing any code at all. From there on, writing any code and more specialized pinning behavior requires you to read into the documentation where we warn about pinning dangers.

**Comment by kcharwood** [comment]
I spoke with the Apple Engineering Security team in depth last week in the WWDC labs, and they agreed there was no additional security value in validating the entire chain. Their own implementation pins against only one certificate in the chain. It's important to understand the trade offs of what level to pin against, but once that decision is made, there is no value in pinning against a higher cert once that has been done.

Unless someone can provide a **specific** vulnerability that pinning against the entire chain provide more security than pinning against a single cert, I'll be deprecating the entire chain validation in a future release.

**Comment by corocraft** [comment]
I have a question regarding validatesCertificateChain. 
When this configuration in AFSSLPinningMode.PublicKey and validatesCertificateChain = true is verified the entire SSL certificate chain, right? and when validatesCertificateChain = false is just validated the first certificate chain?

I don't know because when validatesCertificateChain = false work for me. Maybe the form of the entire chain is incorrect. is it correct to use the following code to get the entire chain and work validatesCertificateChain = true?
openssl s_client -connect example.com:443 </dev/null 2>/dev/null | openssl x509 -outform DER > example.cer

**Comment by paventuri** [comment]
@kcharwood - I would like to know how far you guys have improved it so far. Is there any branch being updated? Do you have any ETA for 2.6.0?

Thank you.

**Comment by kcharwood** [comment]
#2856 is now up for review. Please direct all conversation to that pull request.

:beers:
