### ISSUE TITLE
make AFNetworking allowing ANY self-signed certificate without adding it in the project?

### ISSUE THREAD

**Issue by davi01100100** [AFNetworking/AFNetworking#2776]
I have this issue and I made many attempt to solve it, here the problem:
I need a connection with Self Signed Certificates. I found many responses where we need to put the CER or PER into the project. But in my case I just can't because I have to connect to many servers. Some people argue that iOS is disabling that because security reason, but in fact it's untrue. First, in safari it's working, and most importantly, the NSURLConnectionDelegate allow it.

Exemple of code that doesn't work:
```objective-c
    - (AFHTTPRequestOperation *) createOperation:(NSString *)protocol to: (NSString *)service withBody: (NSString *)json{

        AppDelegate *appDelegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
        NSString *url=[NSString stringWithFormat:@"%@%@",appDelegate.urlSecure, service];
        NSLog(@"BoxDelegate - create operation to %@",url);

        //here the policy attempts
        AFHTTPRequestOperationManager *manager = [[AFHTTPRequestOperationManager alloc] initWithBaseURL:[NSURL URLWithString:url]];
        manager.securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeNone];
        manager.securityPolicy.allowInvalidCertificates = YES;
        manager.securityPolicy.validatesCertificateChain = NO;
        [manager setRequestSerializer:[AFHTTPRequestSerializer serializer]];
        [manager.requestSerializer setAuthorizationHeaderFieldWithUsername:appDelegate.email password:appDelegate.pass];

        NSError *error = nil;
        NSMutableURLRequest *request = [manager.requestSerializer requestWithMethod:protocol URLString:url parameters:nil error:&error];
        NSData *body = [json dataUsingEncoding:NSUTF8StringEncoding];
        [request setHTTPBody:body];
        [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
        AFHTTPRequestOperation *operation = [[AFHTTPRequestOperation alloc] initWithRequest:request];
        return operation;
    }
```
(FYI I also open a question on SO: http://stackoverflow.com/q/30706480/4406065?sem=2)

**Comment by kcharwood** [comment]
If you set the policy to `PinningModeNone`, and allow invalid certificates set to YES, it should work.

But I would _STRONGLY_ suggest not doing that. Anyone could be a man in the middle with that configuration.

**Comment by 7934345** [comment]
AFSecurityPolicy.m

if (self.SSLPinningMode == AFSSLPinningModeNone) {
        return self.allowInvalidCertificates || AFServerTrustIsValid(serverTrust);
}

its not going to check self signed certificate!

**Comment by NarutoYq** [comment]
`
BOOL AFServerTrustIsValid(SecTrustRef serverTrust) {
BOOL isValid = NO;
SecTrustResultType result;
__Require_noErr_Quiet(SecTrustEvaluate(serverTrust, &result), _out);

isValid = (result == kSecTrustResultUnspecified || result == kSecTrustResultProceed);
_out:
return isValid;
}
`
I looked SecTrustEvaluate function at the document,apple say

‘ This function will completely evaluate trust before returning,
possibly including network access to fetch intermediate certificates or to
perform revocation checking. Since this function can block during those
operations, you should call it from within a function that is placed on a
dispatch queue, or in a separate thread from your application's main
run loop. Alternatively, you can use the SecTrustEvaluateAsync function. ’
Whether we need to modify to SecTrustEvaluateAsync function?

**Comment by NarutoYq** [comment]
`static BOOL AFServerTrustIsValid(SecTrustRef serverTrust) {
BOOL isValid = NO;
SecTrustResultType result;
__Require_noErr_Quiet(SecTrustEvaluate(serverTrust, &result), _out);

isValid = (result == kSecTrustResultUnspecified || result == kSecTrustResultProceed);
_out:
return isValid;
}`

I looked SecTrustEvaluate function at the document,apple say

‘ This function will completely evaluate trust before returning,
possibly including network access to fetch intermediate certificates or to
perform revocation checking. Since this function can block during those
operations, you should call it from within a function that is placed on a
dispatch queue, or in a separate thread from your application's main
run loop. Alternatively, you can use the SecTrustEvaluateAsync function. ’
Whether we need to modify to SecTrustEvaluateAsync function?

**Comment by NarutoYq** [comment]
I looked SecTrustEvaluate function at the document,apple say

‘ This function will completely evaluate trust before returning,
possibly including network access to fetch intermediate certificates or to
perform revocation checking. Since this function can block during those
operations, you should call it from within a function that is placed on a
dispatch queue, or in a separate thread from your application's main
run loop. Alternatively, you can use the SecTrustEvaluateAsync function. ’
Whether we need to modify to SecTrustEvaluateAsync function?

**Comment by NarutoYq** [comment]
static BOOL AFServerTrustIsValid(SecTrustRef serverTrust) {
BOOL isValid = NO;
SecTrustResultType result;
__Require_noErr_Quiet(SecTrustEvaluate(serverTrust, &result), _out);
isValid = (result == kSecTrustResultUnspecified || result == kSecTrustResultProceed);
_out:
return isValid;
}

I looked SecTrustEvaluate function at the document,apple say

‘ This function will completely evaluate trust before returning,
possibly including network access to fetch intermediate certificates or to
perform revocation checking. Since this function can block during those
operations, you should call it from within a function that is placed on a
dispatch queue, or in a separate thread from your application's main
run loop. Alternatively, you can use the SecTrustEvaluateAsync function. ’
Whether we need to modify to SecTrustEvaluateAsync function?
