### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-1005 “The network connection was lost

### ISSUE THREAD

**Issue by amitsaxena688** [AFNetworking/AFNetworking#2801]
i am using Afnetworking 2. Some times i get Error message "Error Domain=NSURLErrorDomain Code=-1005 “The network connection was lost". Though if i reset the simulator error goes away. My problem is this happens in my device as well. So with this bug i can't provide a build or i can't ask someone to reset something like their internet connection/wi-fi.Below a complete log of this issue.

Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo=0x7f87e2e0a2c0 {NSUnderlyingError=0x7f87e2c0c9f0 "The network connection was lost.", NSErrorFailingURLStringKey=http://veggykart.com/webservices.php/?cat=cat, NSErrorFailingURLKey=http://veggykart.com/webservices.php/?cat=cat, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=57, NSLocalizedDescription=The network connection was

**Comment by sumitmundra** [comment]
i also face same error

**Comment by alexkotenko** [comment]
The same problem I have  : 
Error: Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo=0x1740faa80 {NSUnderlyingError=0x17004a830 "The network connection was lost.", NSErrorFailingURLStringKey=URL, NSErrorFailingURLKey=URL, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.}

**Comment by bluenose01** [comment]
I had a similar issue, but found the solution here: 
http://stackoverflow.com/a/25996971/682574

Essentially, the underlying NSURLRequest is trying to re-use an HTTP connection that has been dropped by the server. This is apparently caused because the client libraries and your server expect different lifespans for the connection. Or something. Honestly, I'm not 100% sure on the why, but the solutions below all suggest that's what is happening.  

There are 3 different ways to solve this one:
1) Disable KeepAlive on your server
- This will cause new connections to be re-created for each new request. Depending on the pattern in which you talk to the server this may be inconsequential ... or it may be performance concern.
2) Leave KeepAlive ON but make KeepAliveTimeout longer than 30s
- This is the opposite tradeoff as #1.  It will be faster and if you're hitting the server a lot you may notice it.  This will however cause your server to build up connections and reduce the number of concurrent users you can support.

The performance impact of either choice depends somewhat on what server you're running and you should be able to decide with a little googling around for "KeepAlive best practices".

3) Detect the error code and immediately retry the same query.
- When you receive this error - check the error code and immediately retry the same request.  
If the error is caused by using a defunct connection, the new query will create a new connection automagically and should work.  If the network is genuinely gone the you've got bigger problems.

It's possible that this error will come from other sources, but I've tried all 3 of these approaches and each one solved the issue (obviously with different tradeoffs).

**Comment by kcharwood** [comment]
Also see https://github.com/AFNetworking/AFNetworking/issues/2546

**Comment by kingZhou0324** [comment]
Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSErrorFailingURLStringKey=xxxx./20161010/16101000001152.jpg, _kCFStreamErrorCodeKey=-4, NSErrorFailingURLKey=xxxx./20161010/16101000001152.jpg, NSLocalizedDescription=The network connection was lost., _kCFStreamErrorDomainKey=4, NSUnderlyingError=0x18a6b1a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=-4, NSErrorFailingURLStringKey=xxxx./20161010/16101000001152.jpg, NSErrorFailingURLKey=xxxx./20161010/16101000001152.jpg NSLocalizedDescription=The network connection was lost., _kCFStreamErrorDomainKey=4}}}

**Comment by HariGJ** [comment]
Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." 

i met this error.

help me 

Thanks...

**Comment by GoodyIT** [comment]
It happened differently to me.
it worked for my 4g without any problem, but it does not on my friend's 4G or LTE.
we were using different service in the different area.

Anyone has any solution to this

**Comment by bhooshanpatil** [comment]
this might bcoz of bad internet connection ...I spend 2 days to solve the issue ..but then joined dongle to my system and same connection to iPhone ..and guess what, no FIREBASE token issue..
