### ISSUE TITLE
task.taskDescription 

### ISSUE THREAD

**Issue by marinotws** [AFNetworking/AFNetworking#2805]
Hi, following several upload in backgrond, when my app is closed and re-opened by the system to new data going to read the task.taskDescription but the content stored disappeared ... where am I wrong?

    setTaskDidCompleteBlock:^(NSURLSession *session, NSURLSessionTask *task, NSError *error) {
    .....
    NSString *param = task.taskDescription;
    
thanks for the help !

**Comment by marinotws** [comment]
![schermata 2015-06-23 alle 11 15 54](https://cloud.githubusercontent.com/assets/8616947/8304030/c96b28be-19a2-11e5-9a4b-b84ac6b2ef01.png)

this is the result ... I'm pretty sure that the problem is after [task suspend] and then [task resume] ....

**Comment by marinotws** [comment]
please @mattt help ! :-)

**Comment by kcharwood** [comment]
I'm not exactly sure what you are asking here. Can you be more specific, or provide a clearer example on what you expect the output to be?

**Comment by joshsloat** [comment]
I think I have some additional insights that could help to shine a light on the problem.

There was a fix introduced by @tangphillip around tasks and network activity in the following PR: #2477. Of particular note:

```uploadTask.taskDescription = [self descriptionForAllTasks];```

This fix is currently causing some side effects. By setting taskDescription in this manner, when being resurrected from the background, the change is over-writing what the caller may have initially specified for the taskDescription. For example, let’s say I:
 
1. Create an upload task with a taskDescription of “TaskA” (so that I can make conditional “which task was it” decisions in callbacks since I am chaining together several dependent tasks).
1. Kick off my task, crash my app and then relaunch the app. 
1. At that point, I should be able to re-connect to my session and use the taskDescriptions I specified pre-crash (which are persisted properly with the task) to take some specific action if ```[task.taskDescription isEqualToString:@“TaskA”]```.

With the approach implemented in the referenced PR, upon resurrection, “TaskA” is being overwritten with a memory address that is of no use to me and no reliable way of knowing which task finished, reported progress, etc.

**Comment by marinotws** [comment]
sorry for my absence ... @joshsloat He has fully exposed the problem !

**Comment by sust86** [comment]
I'm currently running into the same issue. I need the taskDescription property to map downloadTasks when the application returns.
As far as I see AFNetworking is using taskDescription somehow for the loading indicator observer.
But there is no other way to give background download tasks some payload to identify them later again. 

Is there some alternative option we have?

Thanks

**Comment by kcharwood** [comment]
I think I have my head fully wrapped around the problem. I wish Apple gave us a userInfo rather than a task description. 

We have this pr up right now, but I'm not sure the associated objects would make it back to the host app.

https://github.com/AFNetworking/AFNetworking/pull/2974

**Comment by kcharwood** [comment]
Direct conversation to #2974
