### ISSUE TITLE
AFXMLParserResponseSerializer does not return nil for invalid responses when message is empty

### ISSUE THREAD

**Issue by mozeryansky** [AFNetworking/AFNetworking#2857]
I have a response returning a 202 with an empty body and a content type of application/octet-stream, as expected.

I'm using a compound response serializer and one of the serializers is an AFXMLParserResponseSerializer.

None of my serializers accept octet-stream, so I would expect a nil responseObject. However, in validateResponse:data:error, when the response doesn't match the acceptableContentTypes it will only set a validationError if the response data is non empty:

`if ([data length] > 0 && [response URL]) { validationError=... }`

Then, because the validationError is not nil, the XML serializer's responseObjectForResponse:data:error will not see the error and instead of returning nil, it will return a NSXMLParser initialized with empty data. Because the data is empty and not invalid xml, a NSXMLParser object is returned.

**Comment by mozeryansky** [comment]
I believe the AFXMLParserResponseSerializer is correct to return a NSXMLParser, but it shouldn't when used in a AFCompoundSerializer.

**Comment by lzwjava** [comment]
validationError created by, 
```objc
                validationError = AFErrorWithUnderlyingError([NSError errorWithDomain:AFURLResponseSerializationErrorDomain code:NSURLErrorCannotDecodeContentData userInfo:mutableUserInfo], validationError);
```

so the code is  `NSURLErrorCannotDecodeContentData`

then，

```objc
        if (!error || AFErrorOrUnderlyingErrorHasCodeInDomain(*error, NSURLErrorCannotDecodeContentData, AFURLResponseSerializationErrorDomain)) {
            return nil;
        }
```

it detects the error is NSURLErrorCannotDecodeContentData , so return nil.

why `a NSXMLParser object is returned`  in your case ? 

@mozeryansky

**Comment by mozeryansky** [comment]
The problem is that validationError is not created.

The content type of my response is invalid, so it should return a "unacceptable content-type" error.

However, the data in the response is zero length, so this line:
`if ([data length] > 0 && [response URL]) {`
is false, thus the validationError is never created and error is not set to anything new.

Because validationError is still nil, error will still be nil, and the code you referenced that should return nil will not be called. So the processing continues to the part where it creates the NSXMLParser.

**Comment by kcharwood** [comment]
@mozeryansky Would you like to create PR with a simple test demonstrating the problem and a proposed fix?

Thanks!

**Comment by mozeryansky** [comment]
Sure, I'll try create PR with a test sometime soon.

**Comment by kcharwood** [comment]
@mozeryansky In your case did you have a nil `NSData` or an empty `NSData`?

**Comment by kcharwood** [comment]
I'm not even sure why we have the [data length](https://github.com/AFNetworking/AFNetworking/blob/3_0_0_branch/AFNetworking/AFURLResponseSerialization.m#L119) check since we are guarding against it being nil below. It looks like this check has been in there since at least 2.0.

@cnoon @jshier @kylef thoughts?

**Comment by mozeryansky** [comment]
I don't have the source to the project anymore, but I believe it was an empty NSData because nil would not have crashed my application.

**Comment by kylef** [comment]
@kcharwood I'm not sure why there is a check like this.

I think instead we should only perform this check if there is an actual MIMEType, and adapting the previous if statement as follows:

```objective-c
if (response.MIMEType && self.acceptableContentTypes && ![self.acceptableContentTypes containsObject:response.MIMEType]) {
```

Therefore when no content-type is sent such as for an empty body it will not cause an error. If a content type is provided and we do not know about it, it will then error.

This would make the assumption that if an unknown content-type is provided, we would expect a body.

**Comment by kcharwood** [comment]
I may have thought of a case last night.

Consider a case where a client sends a "write only" command... i.e. something like https://httpbin.org/status/200. There is no body that is actually returned, and the mime type is simply text/html. I wouldnt want that to fail by default, because there is no actual content to parse. Since there is no content parse, I would expect we would down to the status code check, which is exactly what this code is doing.

Is it an "error" if there not a valid content-type and there is no response data to parse anyway, and a valid status code? Based on the scenario above, I would argue there is no error, because there is no thing to parse. The content-type can be ignored for all intensive purposes.

So what should the behavior be for `responseObjectForResponse:data:error:`? If there is no error, and there is no data, should we return nil instead of NSXMLParser inited with nil data? To me it seems unexpected to return a nil object and provide no error.

NSURLErrorDomain does provide a `NSURLErrorZeroByteResource` error, but again I don't actually think this an error to begin with, because you have a valid status code with nothing to parse.

My current viewpoint is to leave as is. Thoughts @cnoon @jshier @kylef ?

**Comment by cnoon** [comment]
I'm with you on leaving the validation logic as is @kcharwood. We are not handling this quite right in Alamofire yet. You only want to throw a content validation error if there was actual data returned. If you don't ensure data was actually returned, you get into some weird cases. For example, if no data is returned and the server doesn't return a `Content-Type` header, I've seen the `response.MIMEType` come back as `text/plain`.

As for the `responseObjectForResponse:data:error:`, it seems it should return `nil` IMO if there isn't any data. I don't have all the context there, but that makes the most sense to me.
