### ISSUE TITLE
Success and Failure block are not called or  blocked by some reasons.

### ISSUE THREAD

**Issue by changkaizhao** [AFNetworking/AFNetworking#2891]
I have following code in a global concurrent queue.      

        
 ```       
   dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{

 __weak __typeof(self)weakSelf = self;
    NSDictionary *paramDic = [self getRequestParam];
    AFHTTPRequestOperationManager *ROManager = [AFHTTPRequestOperationManager manager];
    ROManager.responseSerializer.acceptableContentTypes = [NSSet setWithObject:@"text/html"];
    [ROManager.requestSerializer willChangeValueForKey:@"timeoutInterval"];
    ROManager.requestSerializer.timeoutInterval = 10.f;
    [ROManager.requestSerializer didChangeValueForKey:@"timeoutInterval"];
    NSString *urlString = [[NSBundle mainBundle] pathForResource:@"URL_Config" ofType:@"plist"];
    NSDictionary *plistDic = [[NSDictionary alloc] initWithContentsOfFile:urlString];
   
 [ROManager POST:[plistDic objectForKey:@"CHECK_UPDATE_URL"] parameters:paramDic success:^(AFHTTPRequestOperation *operation, id responseObject) {

 } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
}];
});
```
MY PROBLEM is :  the success or failure block are never called,if I set a breakpoint while app is running, it goes into the block.  really weird .  I really can't  figure out the reason.. HELP!

**Comment by hardikdevios** [comment]
@changkaizhao i dont know why you are putting this in ```dispatch_async``` because  every AF request is by default Async , try to remove ```dispatch_async``` let me see it can help you to debug this issue .. 

i also recommend https://github.com/AFNetworking/AFNetworkActivityLogger  **AFNetworkActivityLogger** this is best tool to debug each and every request you perform through AFNetworking. Let me know this will surely going to solve your problem very easily.

**Comment by changkaizhao** [comment]
@hardikdevios  thank you bro, I've solved my problem. I will try AFNetworkActivityLogger, thanks for your suggestion.
