### ISSUE TITLE
Requests fails with -999 error code

### ISSUE THREAD

**Issue by danielcrisan** [AFNetworking/AFNetworking#2895]
Hi, randomly my GET request from an https server fails with message: canceled and error code -999

**Comment by hardikdevios** [comment]
@danielcrisan This is not AF issue try to search this error Code 

***See this http://stackoverflow.com/questions/16073519/nsurlerrordomain-error-code-999-in-ios***

i also recommend https://github.com/AFNetworking/AFNetworkActivityLogger  **AFNetworkActivityLogger** this is best tool to debug each and every request you perform through AFNetworking. here you will see why you are Getting this ***999*** Code.

**Comment by gonghao** [comment]
Yes, I met the same problems with GET request randomly.

```
2015-09-16 19:11:22.650 EstelBeta[11932:4127174] GET 'https://xxxx/v1/constant/ios'
2015-09-16 19:11:22.651 EstelBeta[11932:4127174] GET 'https://xxxx/v1/notification/count'
2015-09-16 19:11:22.653 EstelBeta[11932:4127174] 200 'https://xxxx/v1/constant/ios' [0.0030 s]
2015-09-16 19:11:22.660 EstelBeta[11932:4127174] [Error] GET '(null)' (0) [0.0034 s]: Error Domain=NSURLErrorDomain Code=-999 "未能完成操作。（“NSURLErrorDomain”错误 -999。）" UserInfo=0x14552890 {NSErrorFailingURLKey=https://xxxxx/v1/notification/count}
2015-09-16 19:11:22.680 EstelBeta[11932:4127174] AFNetworking error code: -999, domain: NSURLErrorDomain, description: 未能完成操作。（“NSURLErrorDomain”错误 -999。）
```

This happened when previous one request hasn't complete and the other one sends. But I don't think it should be a problem when it is in this situation. Why I cannot just send two request the same time?

Thank you.

**Comment by gonghao** [comment]
I found it's possible my fault to cancel the previous in somewhere under some situation, so it occurred randomly.

I would give more information if there is new found.

Thank you.

**Comment by josecostamartins** [comment]
This is also happening to me, both with iOS 8.4.1 and 9.0.2, but only on the device. When using the simulator there are no errors.

Also, the strange thing is that the errors are not occurring in my AFHTTPSessionManager subclass, but in the AFNetworking+UIImageView category, the error is fired in the setImageWithUrl method of the aforementioned category. 

Right now i have a StartCom Class 1 Primary Intermediate Server CA. This cert has no transparency certificate, could this be the problem?

Any help is very welcome,
thanks in advance

**Comment by kcharwood** [comment]
The only place `NSURLErrorCancelled` (-999 for NSURLErrorDomain) is set is in `cancelConnection` for `AFURLConnectionOperation`. I recommend breakpointing through code, and trying to understand how that cancel method was triggered.

:beers:

**Comment by josecostamartins** [comment]
I found my problem.

I was preloading a subset of data (3 items) that i have from a previous controller/network call before i made another call.

The problem is (probably) a racing condition. When i preloaded the subset, the setImageWithURL method was being called inside cellForRowAtIndexPath. At the same time, the array with data from the server with the entire dataset would arrive and would begin the entire process all over again.

If all 3 calls to setImageWithURL had finished before the complete set arrived, no problems would occur. But, if even 1 of the images were still being downloaded the cancelling would occur and would propagate throughout the new setImageWithURL requests... Thus making me remove the rare threads of hair i still have. 

I fixed by using the easiest path, i no longer use the subset before making the call for the entire set.

Maybe cancelling all requests prior do changing the datasource array and tableview reloadData would fixed, but i did not try that.

P.S.: Just posted this in case someone falls into the same problem.

**Comment by KBvsMJ** [comment]
I like this set:
 AFSecurityPolicy *policy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeNone];
        sessionManager.securityPolicy = policy;

or:
  NSSet *certificates = [AFSecurityPolicy certificatesInBundle:[NSBundle mainBundle]];
       AFSecurityPolicy *policy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModePublicKey withPinnedCertificates:certificates];
