### ISSUE TITLE
totalBytesExpectedToRead == -1; Content-Length is set

### ISSUE THREAD

**Issue by flagoworld** [AFNetworking/AFNetworking#2932]
I am trying to download a 25MB file from my server. The server is sending the necessary headers that I know about and `operation.response.expectedContentLength` correctly reflects the `Content-Length`. However in `setDownloadProgressBlock`, `totalBytesExpectedToRead` is always -1.

I don't see anything I'm doing wrong, so I think this is a bug.

**Comment by flagoworld** [comment]
Actually, it seems that expectedContentLength is getting set sometime after it's downloaded, before the completion block and is "-1" in the download progress block. So maybe I am doing something wrong, or maybe there is a bug here...

I stand by my tested and confirmed statement that Content-Length is being set.

**Comment by hardikdevios** [comment]
@flagoworld can you please update your request header and please be make sure that the ```expectedContentLength``` is getting -1 because the content are being set as a **gzip** you have to disable that because **gzip** are compressed objects and usually you wont find the exact length.

So in this case  from server see these how to disable this 
http://stackoverflow.com/questions/9249243/how-to-disable-apache-gzip-compression-for-some-media-files-in-htaccess-file

**As far as i know this is not an AF issue as i have personally faced this in my App**

**Comment by flagoworld** [comment]
Content-Type is application/zip, to be unzipped locally after download.

**Comment by hardikdevios** [comment]
what is ```Content-Encoding``` ?

**Comment by flagoworld** [comment]
I guess I made an incorrect assumption that apache would not try to gzip a zip. A silly thing to do on Apache's part, but I believe you are right that it is double zipping it. Thanks

**Comment by hardikdevios** [comment]
@flagoworld cheers and happy coding
