### ISSUE TITLE
[bug][v2.6.0]cannot change url encoding

### ISSUE THREAD

**Issue by ufolux** [AFNetworking/AFNetworking#2980]
I set manager.stringEncoding to GBK before sending request, but get an error. When I trace the program , It looks like the framework encode my url parameters in UTF-8,then encode the encoded url by GBK. Two times encode cause my error. Anyone meets this problem? I use v2.5.4 now, everything is ok now. I'm appreciate if you can solve the issue. thx

**Comment by izuchy** [comment]
I also cannot change url encoding in v 2.6.0.
so,I use v2.5.4 now too.

**Comment by kcharwood** [comment]
As noted in the [2.6.0 Changelog](https://github.com/AFNetworking/AFNetworking/blob/master/CHANGELOG.md#important-upgrade-notes), the query parameter serialization was migrated in https://github.com/AFNetworking/AFNetworking/pull/2908 to `stringByAddingPercentEncodingWithAllowedCharacters` in order to support watchOS. Apple's new method does not take into account string encoding.

If you need custom query string serialization, you can use `setQueryStringSerializationWithBlock`.
