### ISSUE TITLE
SIGSEGV CFDictionaryGetValue

### ISSUE THREAD

**Issue by mhollis1980** [AFNetworking/AFNetworking#2983]
All,
I've started receiving this stack trace in my crash reports

```
Thread 11 Crashed:
0   CoreFoundation                       0x0000000181e35898 CFDictionaryGetValue + 56
1   Foundation                           0x0000000182e25ef8 _NSSetLongLongValueAndNotify + 68
2   CFNetwork                            0x00000001818eb02c -[__NSCFLocalSessionTask _task_onqueue_didFinish] + 468
3   CFNetwork                            0x00000001818ec6fc -[__NSCFLocalSessionTask connection:didFinishLoadingWithError:] + 36
4   CFNetwork                            0x0000000181934be0 __46-[__NSCFURLSessionConnection _task_sendFinish]_block_invoke + 132
5   libdispatch.dylib                    0x000000019352d994 _dispatch_call_block_and_release + 20
6   libdispatch.dylib                    0x000000019352d954 _dispatch_client_callout + 12
7   libdispatch.dylib                    0x00000001935380a4 _dispatch_queue_drain + 1444
8   libdispatch.dylib                    0x0000000193530a5c _dispatch_queue_invoke + 128
9   libdispatch.dylib                    0x000000019353a318 _dispatch_root_queue_drain + 716
10  libdispatch.dylib                    0x000000019353bc4c _dispatch_worker_thread3 + 104
11  libsystem_pthread.dylib              0x000000019370d22c _pthread_wqthread + 812
12  libsystem_pthread.dylib              0x000000019370cef0 start_wqthread + 0


```

I'm wondering if anyone from community has seen this before or can point me in a direction to hopefully solve it. 
A direction I've started looking at is to remove multiple outstanding requests at time to only allowing a single.

```
_sessionManager.operationQueue.maxConcurrentOperationCount = 1;
```

I'm really not sure if it will help but since this seems to be a threading problem, to me anyways, I thought that would be a good start.

Any help would be appreciated. 
Thanks,
Mike.

**Comment by kcharwood** [comment]
What version of AFNetworking are using? It looks exactly like #1477, which has a pretty long history.

**Comment by ivulyov90** [comment]
I have same issue after update to 3.0.4 from 2.6.3.

**Comment by lawicko** [comment]
Same here.

**Comment by csabatuz** [comment]
The issue is definitely still happening with AFNetworking 3.0.x, but probably for very different reasons, as I have not found the trace of the 'observer' code that was the main trigger in AFNetworking 2.

What the log tells, is that this crash is still something that happens when requests finish, and what happens is very likely accessing a freed-up resource.

Enabling Zombies would tell us what resource is this, but since it seems very hard to reproduce in the lab, that would likely not help much.

All I can think of to increase frequency of issue, is to create network conditions, which delay completion of requests. I am thinking, that this would increase the probability of the crash occurring, and combined with Zombies that might give a further clue which can lead to a patch.
