### ISSUE TITLE
App localization issue on iOS with AFNetworking 2.5.4+

### ISSUE THREAD

**Issue by sroymdsol** [AFNetworking/AFNetworking#3061]
We found a localization issue in our app that turned out to be related, oddly enough, to AFNetworking. The problem was that we have code in main.m that failed to have any effect, as though something happened before it that prevented our code from being effective.

After much digging, it appears as though an internal class in AFURLSessionManager.m loads before main.m executes, forcing resources to load too early.

I created a detailed reduction of the problem, which you can find here:

https://github.com/sroymdsol/AFNLocalizationIssue

As explained in the sample project, we know what commit and what code in AFNetworking is responsible for the problem, but the complexity of the code change makes it difficult to know what a good solution would be. For now, we are forced to cap our app to AFNetworking 2.5.3.

Any feedback would be mucho appreciated!

**Comment by kcharwood** [comment]
Thanks for the detailed write up!

Could you provide more explanation around why you are setting the language in main.m? I've localized several apps, and havent ran into that approach before.

**Comment by sroymdsol** [comment]
Good question. For most locales we leave things alone and everything works with the usual localization mechanism. We only intervene and specify the value of `AppleLanguages` for per-region locale combinations that aren't natively supported by iOS.

For example, we have a localization for general Spanish (es) and one specific to the U.S (es-US). But on iOS 8.x, if you set your language setting to Spanish and your region to United States, `[NSLocale preferredLanguages][0]` returns `@"es"`, so the app displays the general Spanish localization instead of the specific U.S. one. This is where we intervene in main.m and set `AppleLanguages` to es-US, which allows the specific localization to be loaded.

(On iOS 9, `[NSLocale preferredLanguages][0]` now properly returns `@"es-US` for this situation.)

Hope this helps.

**Comment by kcharwood** [comment]
That's certainly very interesting. I'm not sure what could be causing this. The method you referenced is simply a method getting called as the class is loaded into the runtime, which _plenty_ of classes would be doing at that time as well.

I can certainly relate to the problem you are trying to solve. iOS 9 has made it much easier going forward.

I'm not sure there is anything to "fix" here since you are doing some non-standard to the system. For your current use case, I'd recommend patching locally and we'll see if anyone else out there reports a similar issue.

The whole reason that code is there is a _very_ nasty issue with a KVO bug and NSURLSession and we have _lots_ of unit tests around it. I'd like to stay away from it if possible.
