### ISSUE TITLE
AFHTTPRequestOperationManager error after few 5 minutes without use

### ISSUE THREAD

**Issue by tommypeps** [AFNetworking/AFNetworking#3107]
I have AFHTTPRequestOperationManager with SLL with config:
```Objective-C
AFSecurityPolicy *securityPolicy2 = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];//AFSSLPinningModePublicKey
[securityPolicy2 setAllowInvalidCertificates:YES];
[securityPolicy2 setValidatesDomainName:NO];
[manager setSecurityPolicy:securityPolicy2];
```

All ok , but after 5 minutes of use app if don't call at AFHTTPRequestOperationManager after call AFHTTPRequestOperationManager recive the next error:
![capture d ecran 2015-10-30 a 10 23 15](https://cloud.githubusercontent.com/assets/1146741/10842316/199e118a-7ef1-11e5-80d8-9d8436a3a336.png)
![capture d ecran 2015-10-30 a 10 23 48](https://cloud.githubusercontent.com/assets/1146741/10842315/197d24e8-7ef1-11e5-8a7d-5c7a8572b1bb.png)

with code comment I resolve the error temporary but I compromise the security if app

Anyone have a solution?

Last version of AFNetworking 
Version iOS 9.0

**Comment by tommypeps** [comment]
resolú!

**Comment by kcharwood** [comment]
I'm unclear if this is resolved or not.

More information about your app (App Transport Security, Domains, URLs, etc) would be needed to debug this issue. I would recommend directing this question to Stack Overflow since this seems to be more of an application specific issue, and if further debugs leads to identifying a bug, I would open a new issue with more detailed information.

Thanks!
