### ISSUE TITLE
SSL Certificate Issue: Error Domain=NSURLErrorDomain Code=-999

### ISSUE THREAD

**Issue by sasojadrovski** [AFNetworking/AFNetworking#3118]
Hey guys,

I am trying to access an API endpoint which uses SSL certificate signed by GoDaddy. When I try to access the endpoint, I get the following error: Error Domain=NSURLErrorDomain Code=-999.

I am not able to resolve this issue, nor I am able to find any references on the internet which could point out what I am doing wrong. I think that it is related to the SSL certificate which is signed by GoDaddy. Does AFNetworking work with SSL certificates signed by GoDaddy?

Your help will be greatly appreciated.

Cheers!

**Comment by kcharwood** [comment]
Hi @sasojadrovski 

AFNetworking works out of the box with any of the trust root certificates installed by iOS, assuming you have your App Transport Security settings enabled correctly for iOS 9.

I would recommend stepping through the `AFSecurityPolicy` class to get a better understanding of what is happening in your application. If you do identify a bug in AFNetworking, please open an issue here. Otherwise, we ask you that direct general support questions to stack overflow so we can keep the github issues listed focused on bug fixes and feature requests.

:beers:

--
 
From our [Contribution Guidelines](https://github.com/AFNetworking/AFNetworking/blob/master/CONTRIBUTING.md):

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by KBvsMJ** [comment]
I like this set ：
NSSet *certificates = [AFSecurityPolicy certificatesInBundle:[NSBundle mainBundle]];
    AFSecurityPolicy *policy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModePublicKey withPinnedCertificates:certificates];
    sessionManager.securityPolicy = policy;
