### ISSUE TITLE
Performance issue on iPhone 4s, iOS 7.1

### ISSUE THREAD

**Issue by NebirosFeR** [AFNetworking/AFNetworking#3176]
In my project I use AFHttpSessionManager. Some requests are executed very slowly only on iPhone 4s, iOS 7.1. Project is compiled with XCode 7.1.1.
I use this code to check requests duration:
```
NSURLSessionConfiguration *sessionConfiguration = [NSURLSessionConfiguration ephemeralSessionConfiguration];
self.manager = [[AFHTTPSessionManager alloc] initWithBaseURL:urlHost sessionConfiguration:sessionConfiguration];
NSDate *requestStart = [NSDate date];

[self.manager POST:requestURL parameters:requestParameters
 success:^(NSURLSessionDataTask *task, id responseObject) {

        NSDate *requestFinish = [NSDate date];
        NSTimeInterval duration = [requestFinish timeIntervalSinceDate:requestStart];
        NSLog(@"REQUEST DURATION = %f", duration);
}
```

For some requests REQUEST DURATION is 50-60 seconds only on iPhone 4s, iOS 7.1. On other devices and OS it works fine.

Example of described request:
```
POST /api_method.json?lat=100.72401332021572&long=60.53534064818596&hashCode=asd HTTP/1.1
Host: mysite.com
Accept: */*
Authorization: Basic Z2VnaW1vYmlsZ...
Accept-Encoding: gzip, deflate
Accept-Language: en-US;q=1, ru-US;q=0.9
X-USERTOKEN: <token>
Content-Type: application/x-www-form-urlencoded
Content-Length: 70
User-Agent: MyAppName/1.3.0 (iPhone; iOS 7.1; Scale/2.00)
Connection: keep-alive
X-Device-ID: <device id>
Cookie: PHPSESSID=rk5ekfmge5n6md3m2a958i0vq5

body:
apiAccessKey=<key>&apiSecretKey=<key>
```
Real duration of this http request is 534 ms (I saw it in Charles proxy). I also checked that proxy does not affect REQUEST DURATION.

I excluded all my other code, so I am sure that there is a problem with POST method performance of AFHttpSessionManager. Also I discovered, that http request begins only in 50-60 seconds after POST method call.

**Comment by kcharwood** [comment]
Can you include an Instruments trace doing a time profile of application, demonstrating that AFNetworking is the problem here? AFNetworking uses NSURLSession to actually transmit the network request, so I'm guessing there isn't anything network related that we are in control of here here.

It could be serialization, but given the request parameters listed above there is no way that takes a half second to serialize.

Without further specific information or a reproducible example, there is nothing more I can look at.

If you can point to a specific problem with AFNetworking here, please feel free to open a new issue!

:beers:
