### ISSUE TITLE
2.6 branch not compatible with 10.8 anymore because of AFPercentEscapedStringFromString

### ISSUE THREAD

**Issue by altimac** [AFNetworking/AFNetworking#3189]
AFPercentEscapedStringFromString function uses [NSCharacterSet URLQueryAllowedCharacterSet] which is 10.9+ only.

I don't remember the previous version I was using, but it worked on 10.8 and was not using [NSCharacterSet URLQueryAllowedCharacterSet].

Please maintain compatibility with 10.8 since it is *documented* that 2.6.x requires at least 10.8

**Comment by kcharwood** [comment]
Sorry about the confusion there. That breaking change looks like it came from adding support for watchOS 2. Since we don't have a CI system setup for iOS 6 or 10.8, I missed the breaking change there :(. Thats completely my fault. 

Given the current direction of the project, 2.5.4 has been marked as the final release supporting iOS 6 and 10.8. I've updated all of the documentation and the changelog.

Sorry again for that change, but with such low usage, it's not something we plan on revisiting right now.

:beers:

**Comment by altimac** [comment]
Fair enough. I'll revert to 2.5.4.
Thanks for having edited the documentation
