### ISSUE TITLE
Potential hang in `af_resume`

### ISSUE THREAD

**Issue by ZaggerWang** [AFNetworking/AFNetworking#3266]
<img width="553" alt="1" src="https://cloud.githubusercontent.com/assets/11342795/12195788/df55d988-b634-11e5-803d-31aacbddb87a.png">
Crashed when request continuously, I use AFN 3.0.

**Comment by aries-zhang** [comment]
+1

**Comment by kcharwood** [comment]
Is there anyway you could push up an example showing what you are doing?

**Comment by ZaggerWang** [comment]
@kcharwood 
It crashes occasionally.I haven't found the rule. I just use the app normally, and it crashes sometimes.
Here is the main code.
<img width="901" alt="2" src="https://cloud.githubusercontent.com/assets/11342795/12256067/4bdf2944-b935-11e5-89cd-29060e9556ac.png">
<img width="948" alt="3" src="https://cloud.githubusercontent.com/assets/11342795/12256069/4e005086-b935-11e5-86c9-748be9241be4.png">

**Comment by kcharwood** [comment]
There are no underlying changes here with AFN 2.x and AFN 3.0, so I'm not sure the library version affects anything here. There also isn't much information in that crash screenshot.

Could you include a few crash log? Can you provide more information around OS version? Does it crash across OS versions? Have you come up with any test that can repro the crash?

**Comment by ZaggerWang** [comment]
I found that it is not a crash，it is a thread blocking. When I suspend the thread like the blow image shows, everything is back to normal. But I don't know why, and I still don't know how to reappear it, it happens occasionally when I operate crazily.

![1](https://cloud.githubusercontent.com/assets/11342795/12320236/7df986be-bae2-11e5-9662-af371502c49b.jpg)

**Comment by kcharwood** [comment]
Hmmmm. That is very interesting...

We've made lots of improvements to the way af_resume works to prevent hanging. At this point, that code is very defensive to prevent this issue. I wonder if there is some sort of conflict with another library swizzling `resume` there.

There could also be an issue with a third party library including their own (old version) of AFNetworking that was less defensive, and loading after the main AFNetworking lib is loaded into the runtime. We had a pretty long issue recently on that front. 

In that case, that was an infinite recursion, not a thread block.

Without anything reproducible here, this will be really hard to trace down.

**Comment by ZaggerWang** [comment]
There is no other library swizzling ***resume***, but two libraries use runtime, they are MJExtension and MJReresh. I am trying to find the way to reappear it, thank you.

**Comment by kcharwood** [comment]
If you want the full history of the work done in `af_resume`, [this](https://github.com/AFNetworking/AFNetworking/pull/2702#issuecomment-100413218) is a good place to start.

**Comment by raymondchau-sinodynamic** [comment]
Currently I am facing a similar situation, which is easily reproduced in iOS9.
My app flow is like this:
1. download a zip file list from server
2. download those files and write to document directory
3. unzip those files to document directory
4. let the app run normally after unzip finished

Then, I will randomly encounter "HTTP request freezing". I can't send out HTTP request for a period of time, maybe 1second, maybe 2 mins. I can see it from my charles/wireshark, which is having no HTTP request thrown out.

The zip library I am using is https://github.com/mattconnolly/ZipArchive, but even I tried https://github.com/ZipArchive/ZipArchive, I still meet this bug.

**Comment by kcharwood** [comment]
Can anyone isolate this issue when _only_ using AFNetworking, and no other third party library?

**Comment by molon** [comment]
+1
Does someone knows which version has no this problem please?

**Comment by molon** [comment]
I found the reason, but I dont know why..

Look at this image below,  the crash is because of `$x3 == 0x0000000`.
![image](https://cloud.githubusercontent.com/assets/3739161/17297864/16b05cb2-583a-11e6-8a95-e74872f5f804.png)

The image below shows the method who calls `HTTPParser` method. I found it calls `HTTPBodyData` method upon.
![image](https://cloud.githubusercontent.com/assets/3739161/17297845/00494470-583a-11e6-8498-af2f0b31b376.png)

Then I remember that I have print a log for request with the dataTask after calling `resume` method. I guess it's dangerous, so I remove it, then the crash disappears... I dont know why, but it's useful...
![image](https://cloud.githubusercontent.com/assets/3739161/17298078/16688e40-583b-11e6-8f8b-11ae4e4cafdc.png)

**Comment by albertjson** [comment]
![dbb0e052-ff62-4bd7-95d4-055ab7011d9c](https://cloud.githubusercontent.com/assets/3380497/17322060/3c72bd16-58ce-11e6-8eec-d9a648ecd572.png)

i use AFNetworking version is 2.6.3 ,why so many crash in my production app ? 
i have no detail crash log , @kcharwood thinks !!!

**Comment by dangercheng** [comment]
@molon I found the difference!
when i send the request, then got the NSURLSessionDataTask instance, Then i just log the request headers, like bellow code:
Continue sending requests. 
![crash1](https://cloud.githubusercontent.com/assets/5669786/25744533/02f5bfec-31cd-11e7-8678-2ab3b5f7f635.png)
the above crash happened occasionally.
Next, i use the originalRequest instead of currentRequest, the crash didn't happen!
![crash2](https://cloud.githubusercontent.com/assets/5669786/25744547/1233e6aa-31cd-11e7-9ad2-c660cbb66211.png)
I guess, dose AF do something with the currentRequest.allHTTPHeaderFields when requesting? @kcharwood

**Comment by molon** [comment]
@dangercheng I think it does not matter to AFNetworking，just because NSURLRequest is not thread-safe. It's will be used in async thread after `resume`. So we must ensure that don't use it when it's requesting.

**Comment by jasenhuang** [comment]
@molon absolutely you're right，it works after i remove my log of http header fields and !

**Comment by boai** [comment]
+1
