### ISSUE TITLE
AFURLSessionManager not dealloc?

### ISSUE THREAD

**Issue by tujinqiu** [AFNetworking/AFNetworking#3268]
use AFURLSessionManager to perform a data task like this:

NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];

NSURL *URL = [NSURL URLWithString:@"http://example.com/upload"];
NSURLRequest *request = [NSURLRequest requestWithURL:URL];

NSURLSessionDataTask *dataTask = [manager dataTaskWithRequest:request completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {
    if (error) {
        NSLog(@"Error: %@", error);
    } else {
        NSLog(@"%@ %@", response, responseObject);
    }
}];
[dataTask resume];

but the AFURLSessionManager instance manager did not dealloc. Why?

**Comment by kcharwood** [comment]
As discussed in the [NSURLSession](The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session, your app leaks memory until it exits.) docs:

> The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session, your app leaks memory until it exits.

You must call `invalidateSessionCancelingTasks:` in order to properly release the session manager, since NSURLSession maintains a strong reference to its delegate.
