### ISSUE TITLE
setImageWithURLRequest does NOT work when the file has no file extension...any help?

### ISSUE THREAD

**Issue by ihomecall** [AFNetworking/AFNetworking#3298]
I want to show this image
http://files.parsetfss.com/181dfc1b-0f21-4364-b87f-830ad854a26a/tfss-7ba71e86-2b90-4aaf-9345-36012442002d-file

but the setImageWithURLRequest function seems to neglect this file... how can I force it?

**Comment by richardgroves** [comment]
From the URL it looks like you are using Parse.com. I found that I needed
the set the 'name' parameter of the PFFile I uploaded to include the file
type extension (eg .jpg or .png) otherwise the URL doesn't have any type
information in it and so the receiving code has no idea what type of image
it is getting from that URL.

But if you are using Parse why not just use their download methods on
PFFile to get the image? You are going to have to be authenticated against
Parse to access that URL.

On Sat, Jan 16, 2016 at 5:58 AM, ihomecall <notifications@github.com> wrote:

> I want to show this image
>
> http://filesparsetfsscom/181dfc1b-0f21-4364-b87f-830ad854a26a/tfss-7ba71e86-2b90-4aaf-9345-36012442002d-file
>
> but the setImageWithURLRequest function seems to neglect this file how can
> I force it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AFNetworking/AFNetworking/issues/3298>.
>



-- 
Richard Groves
Technical Director | NoodlFroot

M: +44 (0)7962 054 163

www.noodlfroot.com

NoodlFroot Limited is a company registered in England and Wales with
registration number 07245048.
Registered office: 20-22 Wenlock Road, London, N1 7GU.

**Comment by ihomecall** [comment]
hi, Richard. Thanks for the hint on how to let Parse save the extension! that helps me out! 
The reason I did not use download method is that I am using a third party slide module which accepts image urls as input.   Now, I still think logically the setImageWithURLRequest function of  AFNetworking should still download the file when no file extension available.

**Comment by ihomecall** [comment]
You're right! Once I added the name of the file along with the contentType, Parse stores the name as needed.

Old code:
PFFile(data: thumbImageData)

Fixed code:
PFFile(name: "thumb.jpg", data: thumbImageData, contentType: "image/jpeg")

**Comment by kcharwood** [comment]
You need to return a content type so AFNetworking knows how to parse it.
