### ISSUE TITLE
Unable to save file after downloading with downloadTaskWithRequest

### ISSUE THREAD

**Issue by syedabdulsamad** [AFNetworking/AFNetworking#3388]
Hi,

I am downloading a video file. The whole file seems to be downloaded successfully but when i try to get the attributes of the saved file. I get this error.

`Error Domain=NSCocoaErrorDomain Code=260 "The file “7598-Y2TKGNGSEG93SIT.mp4” couldn’t be opened because there is no such file." UserInfo={NSFilePath=file:///var/mobile/Containers/Data/Application/5EE2DF18-81D2-4913-9699-08AC921B740E/Documents/video/7598-Y2TKGNGSEG93SIT.mp4, NSUnderlyingError=0x1491037d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

i am using `downloadTaskWithRequest` method on `NSURLSessionConfiguration` and here is my complete code. 

```
- (void)downloadFile:(MyObject *)myObj progress:(void (^)(float))progress success:(void (^)(NSString *filename))success failure:(void (^)())failure {
  
  
  NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
  AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];
  
  NSURL *URL = [NSURL URLWithString: myObj.downloadUrl];
  NSURLRequest *request = [NSURLRequest requestWithURL:URL];
  
  NSURLSessionDownloadTask *downloadTask = [manager downloadTaskWithRequest:request progress:^(NSProgress * _Nonnull downloadProgress) {
    NSLog(@"Completed : %f", downloadProgress.fractionCompleted);
    dispatch_async(dispatch_get_main_queue(), ^{
      [self progressBlocksForUrl: myObj.archiveUrl withProgress:downloadProgress.fractionCompleted];
    });
  } destination:^NSURL * _Nonnull(NSURL * _Nonnull targetPath, NSURLResponse * _Nonnull response) {
    NSLog(@"Destination");
    NSURL *url = [NSURL URLWithString:myObj.archiveUrl];
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
  	NSString *videoPath = [NSString stringWithFormat:@"/%@/%@", @"video", [url lastPathComponent]];
  	NSString *fullPath = [[paths firstObject] stringByAppendingPathComponent:videoPath];
    return  [NSURL fileURLWithPath:fullPath];
   } completionHandler:^(NSURLResponse * _Nonnull response, NSURL * _Nullable filePath, NSError * _Nullable error) {
     
     
     NSHTTPURLResponse * myresponse = (NSHTTPURLResponse *)response;
     NSLog(@"Video downloaded, headers: %@", [myresponse.allHeaderFields description]);
     
     
    NSLog(@"CompletionHandler");
    if(error) {
      NSLog(@"Error downloading video from %@: %@", myObj.archiveUrl, [error description]);
      [self failureBlockForUrl:myObj.archiveUrl];
    } else{
    
      NSError *fileError;
      NSDictionary *fileAttributes = [[NSFileManager defaultManager] attributesOfItemAtPath:[filePath absoluteString] error:&fileError];
    
      if (fileError) {
        NSLog(@"ERR: %@", [fileError description]);
        [self failureBlockForUrl:myObj.archiveUrl];
      } else {
        NSNumber *fileSizeNumber = [fileAttributes objectForKey:NSFileSize];
        long long fileSize = [fileSizeNumber longLongValue];
        NSLog(@"File %@ with size %lld downloaded!", filePath, fileSize);
        [self completionBlocksForUrl:myObj.archiveUrl withFilename:[filePath absoluteString]];
      }
    }
    
  }];
  [downloadTask resume];
}
```
Does any body have any clue what i am doing wrong here?

**Comment by jasonhotsauce** [comment]
Can you add an observer for notification with name `AFURLSessionDownloadTaskDidFailToMoveFileNotification`? See if the actual move is failed?

**Comment by darrenclark** [comment]
For this line:

```
NSDictionary *fileAttributes = [[NSFileManager defaultManager] attributesOfItemAtPath:[filePath absoluteString] error:&fileError];
```

I believe you need to pass it the path (`[filePath path]`) instead of the URL string (`[filePath absoluteString]`)

**Comment by yyn1110** [comment]
hi  I find same issue ;
Error Domain=NSCocoaErrorDomain Code=516 "“CFNetworkDownload_iLFT1R.tmp” couldn’t be moved to “Documents” because an item with the same name already exists." UserInfo={NSSourceFilePathErrorKey=/Users/yangyanan/Library/Developer/CoreSimulator/Devices/5E57226F-A8B2-42F6-A753-6C049130783D/data/Containers/Data/Application/8BD829E9-BF34-4E71-B561-551377AFE118/tmp/CFNetworkDownload_iLFT1R.tmp, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/yangyanan/Library/Developer/CoreSimulator/Devices/5E57226F-A8B2-42F6-A753-6C049130783D/data/Containers/Data/Application/8BD829E9-BF34-4E71-B561-551377AFE118/Documents/adImage@2.jpg, NSFilePath=/Users/yangyanan/Library/Developer/CoreSimulator/Devices/5E57226F-A8B2-42F6-A753-6C049130783D/data/Containers/Data/Application/8BD829E9-BF34-4E71-B561-551377AFE118/tmp/CFNetworkDownload_iLFT1R.tmp, NSUnderlyingError=0x7f87eae1a2e0 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}
in - (void)URLSession:(NSURLSession *)session
      downloadTask:(NSURLSessionDownloadTask *)downloadTask
didFinishDownloadingToURL:(NSURL *)location method
and post this notification :AFURLSessionDownloadTaskDidFailToMoveFileNotification
class is AFURLSesstionManager.m

**Comment by jasonhotsauce** [comment]
@yyn1110 Just like the error tells you, there is a file with the same name already exists in the file path. This to me is more like a consumer's responsibility to make sure the `downloadFileURL` you passed to session manager is a valid file URL to move download files to. AFNetworking shall not handle this error for you.

**Comment by kcharwood** [comment]
That's the intended use case @jasonhotsauce . You are correct :beers:

**Comment by Light413** [comment]
thanks，resolve my question.
