### ISSUE TITLE
Does 2.6.2 support ipv6?

### ISSUE THREAD

**Issue by rollingstoneW** [AFNetworking/AFNetworking#3496]

**Comment by kcharwood** [comment]
As lined out in Apple's [support docs](https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1), using CFNetwork and NSURLSession will allow you to support IPV6.

However, I don't think the reachability classes support IPV6.

We would entertain potentially releasing a patch version of AF 2.x that supports it, given the announcement from Apple.

**Comment by rollingstoneW** [comment]
Thanks,appreciate that.

**Comment by nakscool** [comment]
ETA for the patch version of AF 2.x?

**Comment by zhangshijian** [comment]
hi ， Did reachability of 2.x  has  supportted IPv6?

**Comment by sdyxch** [comment]
+1

**Comment by ryancrosby** [comment]
Apple updated their reachability example to support IPv6, the [readme](https://developer.apple.com/library/ios/samplecode/Reachability/Listings/ReadMe_md.html#//apple_ref/doc/uid/DTS40007324-ReadMe_md-DontLinkElementID_11) has pointed out the changes that were made that pertain to IPv6. It seems that since AFNetworking is using SCNetworkReachabilityCreateWithName and SCNetworkReachabilityCreateWithAddress, it will work with IPv6. Additionally, using the IP of 0.0.0.0 is valid in sharedManager initializer because it works on an IPv6 network.

I have been digging into this for several hours now, so wouldn't mind another opinion.

**Comment by kcharwood** [comment]
Thanks for the notes here @ryancrosby.

Obviously we're still a bit confused in terms of what this all means from an app rejection standpoint. If we can avoid rev'ing 2.x, thats obviously the best path to choose here.

Anyone else have any insight?

**Comment by abournier** [comment]
I made tests with 2.6.2 on my app creating a NAT64 sharing connection from my mac (as Apple recommended), and all seems to work.

Another option is to replace the Reachability class of 2.6.x with the last version 3.x of the reachability class. It compiled for me without problems...

**Comment by hei9gag** [comment]
I also test my app in version 2.5.2. It seems everything work fine in NAT64 sharing network

**Comment by 249687zhang** [comment]
where I could get  a patch version of AF 2.x that supports ipv6 ? please help me

**Comment by AdrianaPineda** [comment]
Hi! 
Same question as @249687zhang 
Im using version 2.5.3 of AFNetworking

Thanks!

**Comment by jim3ex** [comment]
Hi all,

We also need a patch for reachability in AF 2.x for IPv6. We cannot use AF 3 due to other dependencies.

What is the ETA, please?

**Comment by abournier** [comment]
Maybe you can download last version of AFN, and replace the Reachability classes with the new ones in 2.x. It will compile, I tested it.

**Comment by AdrianaPineda** [comment]
Thanks @abournier I'll give it a try :)

**Comment by purepure** [comment]
+1
