### ISSUE TITLE
NSURLSessionConfiguration cause memory leak,should   [manager.session finishTasksAndInvalidate] or          [self.manager.session invalidateAndCancel] in AFN ?

### ISSUE THREAD

**Issue by ziwen** [AFNetworking/AFNetworking#3543]

**Comment by kcharwood** [comment]
As discussed in the [NSURLSession](The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session, your app leaks memory until it exits.) docs:

> The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session, your app leaks memory until it exits.

You must call `invalidateSessionCancelingTasks:` in order to properly release the session manager, since NSURLSession maintains a strong reference to its delegate.
