### ISSUE TITLE
Leak memory

### ISSUE THREAD

**Issue by qhd** [AFNetworking/AFNetworking#3546]
I think this line `self.session = [NSURLSession sessionWithConfiguration:self.sessionConfiguration delegate:self delegateQueue:self.operationQueue];` in AFURLSessionManager may lead to leak memory.

**Comment by kcharwood** [comment]
As discussed in the [NSURLSession](The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session, your app leaks memory until it exits.) docs:

> The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session, your app leaks memory until it exits.

You must call `invalidateSessionCancelingTasks:` in order to properly release the session manager, since NSURLSession maintains a strong reference to its delegate.
