### ISSUE TITLE
How can I limit total connections count for all AFHTTPSessionManager instances in AFNetworking 3?

### ISSUE THREAD

**Issue by krypt-lynx** [AFNetworking/AFNetworking#3584]
I'm used shared operationQueue for all my AFHTTPRequestOperationManager instances in AFNetworking 2.6, but now AFHTTPRequestOperationManager is removed and AFHTTPSessionManager's operationQueue property is readonly. 

How can I solve this task in AFNetworking 3?

**Comment by fins** [comment]
@krypt-lynx I've just made a fork with similar functionality: `pod 'AFNetworking', :git => 'https://github.com/fins/AFNetworking.git'` I've added there a class AFHTTPOperationSessionManager. You can try to use it instead of AFHTTPSessionManager and set property requestsOperationQueue.maxConcurrentOperationCount to any value. Works fine for me, hope it will fill your needs also.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).

**Comment by krypt-lynx** [comment]
Thanks for rapid response :D
