### ISSUE TITLE
新版本是不是把 AFHTTPRequestOperationManager 类去掉了？

### ISSUE THREAD

**Issue by hhb19900618** [AFNetworking/AFNetworking#3600]

**Comment by jaybowong** [comment]
Please read [AFNetworking 3.0 Migration Guide](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide).
You should use AFHTTPSessionManager instead of AFHTTPRequestOperationManager.

Please use English next time. 😀

@hhb19900618  AFHTTPRequestOperationManager的确是被移除掉了，现在使用AFHTTPSessionManager，在[AFNetworking 3.0 Migration Guide](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide)里有明确的说明。
可以先看看文档或者搜索一下再问哈。

**Comment by GeekYW** [comment]
是的

**Comment by hhb19900618** [comment]
这下完蛋了，如果更新到最新的3.0 代码全部要改下啊！
另外我没更新3.0  苹果今天让我的app过了？咋回事

**Comment by sunbohong** [comment]
苹果没有检测代码层面是否调用了ipv4相关的api，而是通过检测程序是否可以在ipv6网络下面是否可以正常运行。一般情况下，如果没有直接通过198.12.3.4 这种形式进行网络请求，app都能通过审核。但是为了保险起见，建议你切换到最新的版本进行网络请求。

**Comment by GeekYW** [comment]
IP访问的话肯定会被拒绝的

**Comment by xxxIxxxx** [comment]
不知道 有没有遇到这个问题 ，  当我使用iOS9 访问 **https** 时会报 Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server."     但在 iOS8，iOS10 上是没问题的。

**Comment by skyline75489** [comment]
Please close this issue since there is [Migration Guide](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide).

这个 issue 可以关掉了吧 @hhb19900618  参考 [迁移指南](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide).
