### ISSUE TITLE
A doubt with AFN KVO?

### ISSUE THREAD

**Issue by casscqt** [AFNetworking/AFNetworking#3802]
```
- (void)setNetworkActivityIndicatorVisible:(BOOL)networkActivityIndicatorVisible {
    if (_networkActivityIndicatorVisible != networkActivityIndicatorVisible) {
        [self willChangeValueForKey:@"networkActivityIndicatorVisible"];
        @synchronized(self) {
             _networkActivityIndicatorVisible = networkActivityIndicatorVisible;
        }
        [self didChangeValueForKey:@"networkActivityIndicatorVisible"];
        if (self.networkActivityActionBlock) {
            self.networkActivityActionBlock(networkActivityIndicatorVisible);
        } else {
            [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:networkActivityIndicatorVisible];
        }
    }
}

```

1、in setter method manual KVO，this will trigger twice KVO call-back, why here trigger twice？is this a bug?  
2、why here trigger KVO method, but did not use the KVO call-back？

**Comment by tewha** [comment]
1. Pretty sure you'd be right on 1, except maybe iOS prevent this? You should test it and see what happens.
2. I think AFN resists using KVO internally due to some iOS bugs.

This sequence also seems potentially buggy to me:

        if (self.networkActivityActionBlock) {
            self.networkActivityActionBlock(networkActivityIndicatorVisible);
        } else {
            [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:networkActivityIndicatorVisible];
        }

Pretty sure the value of `self.networkActivityActionBlock` can turn to `nil` between the `if` being evaluated and trying to call the block. I suspect this is all over AFN.
