### ISSUE TITLE
AFNetworkReachabilityManager can't  monitor network in time

### ISSUE THREAD

**Issue by ZMYZMY** [AFNetworking/AFNetworking#3878]
when I run my app in  simulator, I close and open network more times. I keep this operation for the third time, the AFNetworkReachabilityManager can't monitor the status of network.

**Comment by Dast1990** [comment]
me too,When I open the app in the login interface and forget to open the network, then I go to the setting interface to connect the network.After open the network,I return back to App,but I found the reachability can not detect the state change, and Ican not log on successfully.

**Comment by tewha** [comment]
I'm not saying there are no bugs because I don't know, but Dast1990's comment seems like he's trying to use Reachability as a gatekeeper. Don't do that.

Imagine a motion sensitive light. Walking past it turns it on. Reachability tells you if the light is on, not if walking past (networking) it will turn it on. Network first, *then* check. (To horribly stretch this analogy, Reachability also won't tell you if the bulb is burnt out.)

**Comment by Dast1990** [comment]
Got it,thank you very much!

**Comment by dark19940411** [comment]
I'm meeting the same problem as @ZMYZMY does. I use AFNetworkReachabilityManager to monitor my vc for a specific demand, because the vc's appearance will be different under different network contexts. But I can't get the callback for the block I set into the manager after swiftly changing the network status several times(switch between online and offline will do the magic.).

**Comment by WeMadeCode** [comment]
I'm meeting the same problem,but I use the following code to solve the problem
      let manager = AFNetworkReachabilityManager.shared()
        manager.setReachabilityStatusChange { (status) in
            switch (status){
            case AFNetworkReachabilityStatus.reachableViaWiFi:
                print("WiFi")
            case AFNetworkReachabilityStatus.reachableViaWWAN:
                print("Cellular mobile network")
            case AFNetworkReachabilityStatus.notReachable:
                print("No network")
                 manager.startMonitoring()
            case AFNetworkReachabilityStatus.unknown:
                print("unknow network")
                 manager.startMonitoring()
            }
        }
        manager.startMonitoring()

But this method seems to consume too much CPU
