### ISSUE TITLE
I use AFNetworking 3.1.0 using cocoapods, why is rejected saying do not support ipv6?

### ISSUE THREAD

**Issue by liaodalin19903** [AFNetworking/AFNetworking#3880]
My post is here: http://stackoverflow.com/questions/42357641/why-afnetworking-3-1-0-did-not-support-ipv6-in-my-app

**Comment by liaodalin19903** [comment]
someone can help?

**Comment by tewha** [comment]
I believe that Apple's notification and your existing answers show this isn't related to AFNetworking at all.

**Comment by dreampowder** [comment]
I think i have found the solution. The main problem is Cocoapods is setting the "Deployment Target" of Pod Project to "IOS 7.0". so this makes "AFNetworkReachabilityManager.m" class to use old "ipv4" code instad of the new ipv6 block because the "if statement" falls into the wrong side. 

the "__IPHONE_OS_VERSION_MIN_REQUIRED" statement return "7000" because cocoapods deployment target is set as "7.0" instead of useing the same deployment target as the main project. 

```
+ (instancetype)manager
{
    NSLog(@"min iphoneos: %i - %i",__IPHONE_OS_VERSION_MIN_REQUIRED,__IPHONE_OS_VERSION_MIN_REQUIRED);
#if (defined(__IPHONE_OS_VERSION_MIN_REQUIRED) && __IPHONE_OS_VERSION_MIN_REQUIRED >= 90000) || (defined(__MAC_OS_X_VERSION_MIN_REQUIRED) && __MAC_OS_X_VERSION_MIN_REQUIRED >= 101100)
    struct sockaddr_in6 address;
    bzero(&address, sizeof(address));
    address.sin6_len = sizeof(address);
    address.sin6_family = AF_INET6;
    NSLog(@"IPV6 Block");
#else
    struct sockaddr_in address;
    bzero(&address, sizeof(address));
    address.sin_len = sizeof(address);
    address.sin_family = AF_INET;
    NSLog(@"IPV4 Block");
#endif
    return [self managerForAddress:&address];
}
```

**Comment by tewha** [comment]
That looks wrong, yeah. AFNetworking should use the newer API if it's available, regardless of the minimum deployment level: The `#else` case should include a runtime check to use IPv6 when available.

**Comment by tobitech** [comment]
What then is the solution to this, please. My app was rejected for this reason

**Comment by liaodalin19903** [comment]
Can you post the url, shows the issue?






At 2017-04-25 19:16:21, "Oluwatobi Omotayo" <notifications@github.com> wrote:


What then is the solution to this, please. My app was rejected for this reason

**Comment by dreampowder** [comment]
tobitech, the latest cocoapods update made the pod install command set the correct deployment target value. But you can also set it manually but selecting the pods project and set the deployment target somewhere greated than or equal to 9.0

**Comment by tobitech** [comment]
I'm not entirely sure AFNetworking is the issue. Another developer worked on the app and isn't using cocoa pods, my job is to deploy the app. From what I've been reading on SO recently it's like it's because an IP Address was hard coded in the app. "manager" instance type code seems to be correct in the AFNetworkReachabilityManager class. My question is could the URL hardcoded IPAddress cause the problem?

**Comment by dreampowder** [comment]
Yeah, i have also seen some cases in my apps that they just fail some other test and throw out the "ipv6" issue becuase they were testing the app in the ipv6 environment. But i am %100 sure that if you are using afnetworking with cocoapods and your deployment target is below 9.0 you will likely to fail at ipv6 test..

**Comment by tobitech** [comment]
Nigeria @liaodalin19903 Why did you ask?

**Comment by JackLoly** [comment]
@tobitech I finally find my issue is not caused by AFNetworking, it is caused by the rear-end javaer config the server mistakenly, and so in the USA, can not access the server address, the apple auditor rejected with ipv6 issue, is not really ipv6 issue. I have declared this in my answer of the my post. have you check that?

**Comment by tewha** [comment]
You know, we got rejected for an IPv6 issue that turned out to be not related to IPv6 at all as well. I think the IPv6 test might be the most hands-on test Apple does now.

**Comment by NosovPavel** [comment]
Actually this problem is not resolved by AFNetworking team. You can add manually something like this 
`#define SYSTEM_VERSION_GREATER_THAN(v)              ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending)` to AFNetworkReachabilityManager.m file where system version checking by default. 

At the end it should looks like this 

 ```
   if (SYSTEM_VERSION_GREATER_THAN(@"9.0")){
        struct sockaddr_in6 address;
        bzero(&address, sizeof(address));
        address.sin6_len = sizeof(address);
        address.sin6_family = AF_INET6;
        return [self managerForAddress:&address];
    } else {
        struct sockaddr_in address;
        bzero(&address, sizeof(address));
        address.sin_len = sizeof(address);
        address.sin_family = AF_INET;
        return [self managerForAddress:&address];
    }
```

**Comment by EddyLB** [comment]
My app has also been rejected.
Using this [Apple guide](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16), I have realised that the actual code does not indeed follow the IPv6 route using Cocoapods deployment target set as "8.0". So I changed the code as follows to fix the issue.

Could you please update AFNetworking? Thanks.

```
+ (instancetype)manager
{
    if (NSFoundationVersionNumber >= NSFoundationVersionNumber_iOS_9_0) {
        struct sockaddr_in6 address;
        bzero(&address, sizeof(address));
        address.sin6_len = sizeof(address);
        address.sin6_family = AF_INET6;

        return [self managerForAddress:&address];
    } else {
        struct sockaddr_in address;
        bzero(&address, sizeof(address));
        address.sin_len = sizeof(address);
        address.sin_family = AF_INET;

        return [self managerForAddress:&address];
    }
}
```

**Comment by tewha** [comment]
I want you guys to understand I'm not arguing this patch shouldn't be landed. It's important, and it should definitely go in.

But you're not supposed to gate functionality behind reachability. It's considered informational and potentially useful, not definitive. If you're using the results of reachability for anything important, you should address that first.

Having a properly function reachability should improve your app, not make it possible for it to work at all (even under IPv6).

**Comment by kokphinchian1682** [comment]
Sweet thanks girl is coming to

**Comment by tewha** [comment]
The only thing needed here is the developers of the apps need to stop using Reachability as a gate before making a networking attempt. This is a very fundamental thing, and has been discussed in many WWDC talks: network first, check reachability after.
