### ISSUE TITLE
Dose anyone receive this email use AFN

### ISSUE THREAD

**Issue by shujucn** [AFNetworking/AFNetworking#3888]
I received this warning message this morning. When check out code I find AFN use 
static inline void af_swizzleSelector(Class theClass, SEL originalSelector, SEL swizzledSelector) {
    Method originalMethod = class_getInstanceMethod(theClass, originalSelector);
    Method swizzledMethod = class_getInstanceMethod(theClass, swizzledSelector);
    **method_exchangeImplementations(originalMethod, swizzledMethod);**
}
which use the method apple give in the message.

Dose anyone have ideal about this?

> 
’Your app, extension, and/or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with section 3.3.2 of the Apple Developer Program License Agreement and App Store Review Guideline 2.5.2. This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes.

**This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.**

Please perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above before submitting the next update for your app for review.
Best regards,
App Store Review‘
>

**Comment by tewha** [comment]
AFNetworking doesn't do the described behaviour. Swizzling is fine; swizzling based on instructions downloaded via network is not.

**Comment by shujucn** [comment]
@tewha Thanks, I will check other code

**Comment by wangzhangjie** [comment]
I received this warning message too. When check out code I find AFN use
static inline void af_swizzleSelector(Class theClass, SEL originalSelector, SEL swizzledSelector) {
Method originalMethod = class_getInstanceMethod(theClass, originalSelector);
Method swizzledMethod = class_getInstanceMethod(theClass, swizzledSelector);
**method_exchangeImplementations**(originalMethod, swizzledMethod);
}

Apple message :The code referenced in our initial rejection message includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), , **method_exchangeImplementations**(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script
