### ISSUE TITLE
setSecurityPolicy throws exception for nil baseURL

### ISSUE THREAD

**Issue by jcavar** [AFNetworking/AFNetworking#4141]
`AFURLSessionManager`s `baseURL` is `nullable` parameter. If not set you can construct URL manually and use it directly in GET/POST methods. This is I think valid use case but is prevented because `AFURLSessionManager` throws exception if you try to set `securityPolicy` on such manager.

I can see that this change was introduced here:
https://github.com/AFNetworking/AFNetworking/commit/a26a500c1da28f2a44fbc1feea7270bf0fe01ce6

cc @0xced  

Would it be possible to check if `baseURL` == "http" instead of `baseURL` == "https"? Are there any risks in that? Or even explicitly check if `baseURL` == nil

**Comment by rakaramos** [comment]
+1

**Comment by raistlin969** [comment]
+1

**Comment by petrinichav** [comment]
+1 It's weird to terminate app if baseurl is nil.

**Comment by Brukhan** [comment]
+1

**Comment by Dingo203** [comment]
+1  It's unreasonable to terminate without set baseurl and version 3.1.0 didn't have this issue.

**Comment by garyyu** [comment]
+1

**Comment by Herbert8** [comment]
+1

**Comment by fullsailor** [comment]
That's our use case exactly. We pin to an intermediate certificate. And we don't know the exact one of our domains we'll be talking to through the client since some of the content is at different hosts, but they all have certificates issued by the same intermediate. 

At the moment our workaround is to include a baseURL anyway, even though every request includes a full url.
