### ISSUE TITLE
iOS 12 Crash at networkRequestThreadEntryPoint function

### ISSUE THREAD

**Issue by ikbalnamli** [AFNetworking/AFNetworking#4297]
Our users on ios 12 seems to have crash on function networkRequestThreadEntryPoint. What could be the reason? 

Crash Report:

xxx | AFURLConnectionOperation.m line 164+[AFURLConnectionOperation networkRequestThreadEntryPoint:]
-- | --

**Comment by luizperes** [comment]
Same thing here

**Comment by luizperes** [comment]
hey @ikbalnamli, it turns out that for me it was not related to AFNetworking. I was calling multiple concurrent children of a NSManagedContext (Using RestKit) and the threads were changing values at the same time. I solved with:

```
[context performAndWait:^{
...
}];
```

Check this out, it might help you: https://github.com/AFNetworking/AFNetworking/issues/733
