### ISSUE TITLE
WebKit`-[WKNavigation dealloc]     Crashed!

### ISSUE THREAD

**Issue by TheLittleBoy** [AFNetworking/AFNetworking#4546]
version 4.0.0

crash code 1:

    self.webView = [[WKWebView alloc] init];
    NSURLRequest *request = [[NSURLRequest alloc] initWithURL:[NSURL URLWithString:@"https://www.baidu.com"]];
    [self.webView loadRequest:request navigation:[WKNavigation new] progress:nil success:^NSString * _Nonnull(NSHTTPURLResponse * _Nonnull response, NSString * _Nonnull HTML) {
        return HTML;
    } failure:^(NSError * _Nonnull error) {

    }];

crash code 2:

    self.webView = [[WKWebView alloc] init];
    self.navigation = [WKNavigation new];
    NSURLRequest *request = [[NSURLRequest alloc] initWithURL:[NSURL URLWithString:@"https://www.baidu.com"]];
    [self.webView loadRequest:request navigation:self.navigation progress:nil success:^NSString * _Nonnull(NSHTTPURLResponse * _Nonnull response, NSString * _Nonnull HTML) {
        return HTML;
    } failure:^(NSError * _Nonnull error) {

    }];

When the controller is released, it will crash.

How can I create a WKNavigation?

**Comment by jshier** [comment]
Could you provide stack traces for the crashes you're seeing?

**Comment by TheLittleBoy** [comment]
![1](https://user-images.githubusercontent.com/3365421/79706400-b5f6d780-82eb-11ea-85a5-5e79cce1df81.png)

**Comment by glauberlima** [comment]
@TheLittleBoy for those weird stack traces I usually enable **Exception Breakpoint** in order to make XCode stop the execution in the proper line that caused the crash.

<img width="402" alt="Screen Shot 2020-04-20 at 09 22 03" src="https://user-images.githubusercontent.com/1093588/79751360-d8d3bc80-82e8-11ea-9e5d-6c1ed0415383.png">

<img width="475" alt="Screen Shot 2020-04-20 at 09 22 39" src="https://user-images.githubusercontent.com/1093588/79751399-e8530580-82e8-11ea-9015-f69f6ee65030.png">

**Comment by TheLittleBoy** [comment]
@glauberlima It is not work.   You can try run my code 1 or 2.

**Comment by xuhaoranLeo** [comment]
i have the same issue

**Comment by TheLittleBoy** [comment]
@xuhaoranLeo  remove WKNavigation !
